# Injects the social / canonical / icon block into every page head.
#
# Title and description are read back OUT of each page, so this stays a single
# source: edit the <title> and the description on the page, re-run this, and the
# Open Graph and Twitter cards follow. Idempotent — it replaces its own block.
import html
import io
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SITE = "https://mccain-digital.com"

MARK_A = "  <!-- SOCIAL+CANONICAL: generated by tools/add_meta.py, do not hand-edit -->"
MARK_B = "  <!-- /SOCIAL+CANONICAL -->"

PAGES = [
    "index.html",
    "contact.html",
    "services/ai-tools.html",
    "services/web-apps.html",
    "services/websites.html",
    "services/software.html",
    "legal/imprint.html",
    "legal/privacy.html",
    "legal/terms.html",
    "legal/withdrawal.html",
]


def block(rel, title, desc):
    up = "../" if "/" in rel else ""
    url = SITE + "/" + rel
    # the canonical for the front page is the bare domain, not /index.html
    if rel == "index.html":
        url = SITE + "/"
    # What was read back out of the page is MARKUP: a title containing `&mdash;`
    # is the text "—", not the seven characters. Escaping it straight into an
    # attribute produced `&amp;mdash;`, and the social card then showed the
    # entity verbatim. Decode to text first, then escape once.
    esc = lambda s: (html.unescape(s)
                     .replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;"))
    t, d = esc(title), esc(desc)
    return "\n".join([
        MARK_A,
        '  <meta name="theme-color" content="#0d0c0a">',
        '  <link rel="apple-touch-icon" sizes="180x180" href="%sapple-touch-icon.png">' % up,
        '  <link rel="canonical" href="%s">' % url,
        '  <link rel="sitemap" type="application/xml" href="%ssitemap.xml">' % up,
        '  <meta property="og:type" content="website">',
        '  <meta property="og:site_name" content="McCain Digital">',
        '  <meta property="og:locale" content="en_US">',
        '  <meta property="og:url" content="%s">' % url,
        '  <meta property="og:title" content="%s">' % t,
        '  <meta property="og:description" content="%s">' % d,
        '  <meta property="og:image" content="%s/og-image.png">' % SITE,
        '  <meta property="og:image:width" content="1200">',
        '  <meta property="og:image:height" content="630">',
        '  <meta property="og:image:alt" content="McCain Digital — we build the useful kind of AI.">',
        '  <meta name="twitter:card" content="summary_large_image">',
        '  <meta name="twitter:title" content="%s">' % t,
        '  <meta name="twitter:description" content="%s">' % d,
        '  <meta name="twitter:image" content="%s/og-image.png">' % SITE,
        MARK_B,
    ])


for rel in PAGES:
    p = os.path.join(ROOT, rel.replace("/", os.sep))
    s = io.open(p, encoding="utf-8", newline="").read()

    title = re.search(r"<title>(.*?)</title>", s, re.S).group(1).strip()
    m = re.search(r'<meta name="description"\s+content="(.*?)">', s, re.S)
    desc = " ".join(m.group(1).split())

    new = block(rel, title, desc)

    if MARK_A in s:                                   # replace our own block
        a = s.index(MARK_A)
        b = s.index(MARK_B) + len(MARK_B)
        s = s[:a] + new + s[b:]
    else:                                             # insert after the icon link
        anchor = re.search(r'  <link rel="icon"[^>]*>\n', s)
        s = s[:anchor.end()] + new + "\n" + s[anchor.end():]

    io.open(p, "w", encoding="utf-8", newline="").write(s)
    print("meta:", rel)
