# GENERATED by scratchpad/convert_chrome.py from the extraction artefact
# chrome.html - do not edit by hand, edit the artefact and convert again.
#
# The real subpage chrome: the six-dropdown header, the mobile drawer and the
# "Die Seite fragen" pill, lifted out of the start page and re-implemented
# without React. Every number is the one the start page uses; the provenance,
# line by line, is in the artefact's companion chrome.md.
#
# WHY THIS EXISTS
# The first rebuild of the subpages shipped four flat text links as a header.
# The owner: "falscher header". It was: the start page's header is six
# dropdowns with gradient service icons, a promo card, a panel footer, a
# measured indicator and a mobile drawer.
#
# WHAT IS DELIBERATELY NOT HERE
# The DE/EN toggle. There is no second URL to go to - the start page's toggle
# writes localStorage and re-renders from an in-memory dictionary. On a static
# subpage it would either do nothing, or set the START page to English while
# the page underneath stays German and <html lang="de"> keeps saying so.
# content.json is already bilingual, so the day it ships English pages the
# control comes back with somewhere to point.

CSS = """.sprite{position:absolute;width:0;height:0;overflow:hidden}

/* =====================================================================
   HEADER
   Start page: position:fixed, z-index 80, height 72, background
   rgba(255,255,255,.92), backdrop-filter blur(14px) saturate(1.4),
   box-shadow "0 1px 0 #E3E8EE" -> scrolled adds
   "0 10px 30px -18px rgba(10,37,64,.18)", transition box-shadow .3s.

   Deliberate deviation: sticky instead of fixed. The start page is fixed
   because its hero carries clamp(150px,17vw,196px) of top padding to sit
   under it. A prose subpage has no such hero, and fixed would need a
   body padding-top that every page then has to remember.
   ===================================================================== */
.site-head{position:sticky;top:0;z-index:80;
  background:rgba(255,255,255,.92);
  backdrop-filter:blur(14px) saturate(1.4);
  -webkit-backdrop-filter:blur(14px) saturate(1.4);
  box-shadow:0 1px 0 var(--rule);transition:box-shadow .3s}
.site-head[data-scrolled="true"]{
  box-shadow:0 1px 0 var(--rule),0 10px 30px -18px rgba(10,37,64,.18)}
.nav-inner{position:relative;max-width:1440px;margin:0 auto;
  padding:0 clamp(20px,4vw,48px);height:var(--nav-h);
  display:flex;align-items:center;gap:18px}

/* lockup: 34px mark + 14px gap + 18px/600/-.03em wordmark */
.lockup{display:flex;align-items:center;gap:14px;color:var(--ink);flex:none}
.lockup:hover{color:var(--ink)}
.lockup .mark{display:block;flex:none;width:34px;height:34px}
.lockup .word{font-weight:600;letter-spacing:-.03em;font-size:18px;line-height:1}
/* The start page also prints the page kind after the wordmark on subpages
   (pagekit does: "mccain digital / KI-Tools"). Kept - it is the one thing a
   subpage header knows that the start page does not. */
.lockup .sep{color:#C6CEDA;font-weight:400;font-size:18px;line-height:1}
.lockup .kind{font-family:'JetBrains Mono',ui-monospace,monospace;font-size:12px;
  letter-spacing:.06em;color:var(--muted2);font-weight:400;line-height:1}

/* ---- desktop nav ------------------------------------------------- */
.nav-list{position:relative;display:flex;align-items:center;gap:4px;
  margin-left:8px}
.nav-ind{position:absolute;top:50%;height:36px;margin-top:-18px;border-radius:8px;
  background:rgba(10,37,64,.06);opacity:0;pointer-events:none;left:0;width:0;
  transition:left .35s var(--ease),width .35s var(--ease),opacity .2s}
.nav-list[data-open="true"] .nav-ind{opacity:1}
.nav-item{position:relative;display:flex;align-items:center;gap:3px;
  padding:8px 12px;border-radius:8px;font-size:15px;font-weight:500;
  white-space:nowrap;color:var(--ink);opacity:1;transition:opacity .2s}
/* the export dims the OTHER triggers to .6 while a menu is open */
.nav-list[data-open="true"] .nav-item{opacity:.6}
.nav-list[data-open="true"] .nav-item[aria-expanded="true"]{opacity:1}
.nav-item .chev{width:13px;height:13px;opacity:.55;transition:transform .3s}
.nav-item[aria-expanded="true"] .chev{transform:rotate(180deg)}

/* ---- the shared dropdown panel ----------------------------------- */
.nav-caret{position:absolute;top:69px;left:0;width:14px;height:14px;
  background:#fff;transform:rotate(45deg);border-radius:3px;opacity:0;
  pointer-events:none;z-index:2;
  transition:left .35s var(--ease),opacity .2s,visibility 0s .25s;
  visibility:hidden}
.nav-panel{position:absolute;top:76px;left:0;width:560px;height:0;
  background:#fff;border-radius:12px;
  box-shadow:0 30px 90px -20px rgba(10,37,64,.30),
             0 2px 10px rgba(10,37,64,.08),
             0 0 0 1px rgba(10,37,64,.05);
  opacity:0;visibility:hidden;transform:translateY(-6px) scale(.985);
  transform-origin:50% 0;pointer-events:none;overflow:hidden;z-index:1;
  transition:opacity .22s,transform .3s var(--ease),visibility 0s .25s}
/* "fresh" = opening from closed: no left/width/height animation, or the panel
   slides in from wherever it last was. Matches panelTransition in the export. */
.nav-panel[data-move="true"]{
  transition:left .35s var(--ease),width .35s var(--ease),height .35s var(--ease),
             opacity .22s,transform .3s var(--ease),visibility 0s}
.nav-panel[data-open="true"],.nav-caret[data-open="true"]{
  opacity:1;visibility:visible;pointer-events:auto;transition-delay:0s}
.nav-panel[data-open="true"]{transform:translateY(0) scale(1)}
.pane{position:absolute;top:0;left:0;opacity:0;visibility:hidden;
  pointer-events:none;transform:translateX(-28px);
  transition:opacity .25s,transform .35s var(--ease),visibility 0s .25s}
.pane[data-on="true"]{opacity:1;visibility:visible;pointer-events:auto;
  transform:translateX(0);transition-delay:0s}
/* widths are Component.MENU_W, verbatim */
.pane-services{width:780px}
.pane-work{width:540px}
.pane-studio{width:560px}
.pane-process{width:540px}
.pane-resources{width:440px}
.pane-pricing{width:480px}
.pane-grid{display:grid;gap:2px;padding:14px}
.pane-services .pane-grid{grid-template-columns:1fr 1fr 214px;gap:2px 12px}
.pane-studio .pane-grid{grid-template-columns:1fr 1fr;gap:10px;padding:16px}
.mi{display:flex;gap:14px;align-items:flex-start;padding:12px;border-radius:8px;
  color:var(--ink);transition:background .2s}
.mi:hover{background:var(--tint);color:var(--ink);text-decoration:none}
.mi .ic{flex:none;width:36px;height:36px;border-radius:9px;color:#fff;
  display:grid;place-items:center;
  box-shadow:inset 0 1px 0 rgba(255,255,255,.35)}
.mi .ic svg{width:18px;height:18px}
.mi .tx{display:block;min-width:0}
.mi .t{display:flex;align-items:center;gap:8px;font-size:15px;font-weight:600;
  color:var(--ink)}
.mi .d{display:block;font-size:13px;line-height:1.45;color:var(--muted);
  margin-top:3px}
/* "you are here": the dot rides the TITLE, not the flex row - a row-level
   ::after floats in the empty middle of a two-line card and reads as a stray. */
.mi[aria-current="page"] .t{color:var(--acc-text)}
.mi[aria-current="page"] .t::after{content:"";width:6px;height:6px;
  border-radius:50%;background:var(--acc);flex:none}

/* service icon grounds - Component.FLOW, first and third stop */
.ic-ai{background:linear-gradient(135deg,#FF5A8C,#C05CFF)}
.ic-apps{background:linear-gradient(135deg,#6E7BFF,#C05CFF)}
.ic-web{background:linear-gradient(135deg,#FFB46B,#FF8A5B)}
.ic-software{background:linear-gradient(135deg,#C05CFF,#FF5A8C)}
.ic-case-recall{background:linear-gradient(135deg,#6E7BFF,#C05CFF)}
.ic-case-site{background:linear-gradient(135deg,#5FC3FF,#6E7BFF)}
.ic-res{background:linear-gradient(135deg,#1D3B60,#0A2540);
  box-shadow:inset 0 1px 0 rgba(255,255,255,.2)}
.badge{font-size:11px;font-weight:600;color:#1F8A5B;background:rgba(79,207,140,.16);
  padding:2px 8px;border-radius:999px}
.badge.soon{color:var(--muted);background:none;
  border:1px solid rgba(10,37,64,.14);padding:1px 7px}

/* the tall gradient promo card in the Leistungen panel */
.promo{grid-column:3;grid-row:1 / span 2;position:relative;overflow:hidden;
  border-radius:10px;padding:16px;text-align:left;color:#fff;background:var(--navy);
  display:flex;flex-direction:column;justify-content:flex-end;gap:6px;
  min-height:190px;transition:transform .3s}
.promo:hover{transform:translateY(-2px);color:#fff;text-decoration:none}
.promo .flow{position:absolute;inset:-40%;opacity:.9}
.promo .flow i{position:absolute;inset:0;display:block;will-change:transform}
.promo .flow .a{background:
  radial-gradient(42% 46% at 30% 36%,#FF5A8C 0%,transparent 100%),
  radial-gradient(46% 50% at 74% 28%,#FFB46B 0%,transparent 100%),
  linear-gradient(135deg,#FF5A8C,#C05CFF);
  animation:flowA 26s ease-in-out infinite}
.promo .flow .b{background:
  radial-gradient(48% 52% at 66% 72%,#C05CFF 0%,transparent 100%),
  radial-gradient(36% 40% at 22% 78%,#FFB46B 0%,transparent 100%);
  opacity:.85;animation:flowB 32s ease-in-out infinite}
.promo .veil{position:absolute;inset:0;
  background:linear-gradient(180deg,rgba(10,31,68,0) 25%,rgba(10,31,68,.88) 100%)}
.promo span{position:relative}
.promo .live{display:inline-flex;align-items:center;gap:6px;font-size:11px;
  font-weight:600}
.promo .dot{width:7px;height:7px;border-radius:50%;background:#15BE53;
  animation:pulseDot 2.2s ease-out infinite}
.promo .h{font-size:16px;font-weight:700;letter-spacing:-.02em;line-height:1.2}
.promo .s{font-size:12px;line-height:1.45;color:rgba(255,255,255,.85)}
.pane-foot{display:flex;align-items:center;justify-content:space-between;
  gap:16px;padding:13px 22px;background:var(--tint);
  border-top:1px solid rgba(10,37,64,.06);font-size:13px}
.pane-foot .note{color:var(--muted)}
.pane-foot a{font-weight:600;color:var(--ink)}
.pane-foot a.acc{color:var(--acc-text)}
.studio-card{display:block;padding:16px;border-radius:10px;background:var(--tint);
  text-align:left;transition:background .2s;color:var(--ink)}
.studio-card:hover{background:#EEF2F9;text-decoration:none;color:var(--ink)}
.studio-card .k{display:block;font-size:13px;font-weight:600;color:var(--acc-text)}
.studio-card .y{display:block;font-size:26px;font-weight:700;letter-spacing:-.03em;
  color:var(--ink);margin-top:8px}
.studio-card .p{display:block;font-size:13px;line-height:1.5;color:var(--body);
  margin-top:8px}
.stack{display:grid;gap:2px;align-content:start}
.stack .lbl{display:block;font-size:12px;font-weight:600;color:var(--muted);
  padding:6px 12px 4px}
.person{display:flex;gap:12px;align-items:center;padding:9px 12px;border-radius:8px;
  transition:background .2s;color:var(--ink)}
.person:hover{background:var(--tint);text-decoration:none;color:var(--ink)}
.person .av{flex:none;width:34px;height:34px;border-radius:8px;color:#fff;
  font-weight:700;font-size:14px;display:grid;place-items:center}
.person .n{display:block;font-size:14px;font-weight:600;color:var(--ink)}
.person .r{display:block;font-size:12px;color:var(--muted);margin-top:2px}
.step{display:flex;gap:16px;align-items:flex-start;padding:11px 12px;
  border-radius:8px;transition:background .2s;color:var(--ink)}
.step:hover{background:var(--tint);text-decoration:none;color:var(--ink)}
.step .n{flex:none;font-family:'JetBrains Mono',ui-monospace,monospace;
  font-size:12px;font-weight:500;color:var(--acc-text);margin-top:3px}
.step .hd{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}
.step .t{font-size:15px;font-weight:600;color:var(--ink)}
.step .w{font-size:12px;color:var(--muted)}
.step .d{display:block;font-size:13px;line-height:1.45;color:var(--muted);
  margin-top:3px}
.price-head{padding:20px 22px 6px}
.price-head .k{font-size:13px;font-weight:600;color:var(--acc-text)}
.price-head .t{font-size:20px;font-weight:700;letter-spacing:-.025em;
  color:var(--ink);margin-top:6px}
.price-head p{font-size:13px;line-height:1.5;color:var(--muted);margin-top:6px}
.price-row{display:flex;gap:14px;align-items:center;padding:10px 0;
  border-top:1px solid rgba(10,37,64,.08)}
.price-row .n{flex:none;width:26px;height:26px;border-radius:50%;
  background:var(--acc-soft);color:var(--acc-text);
  font-family:'JetBrains Mono',ui-monospace,monospace;font-size:11px;
  font-weight:500;display:grid;place-items:center}
.price-row .t{font-size:14px;font-weight:600;color:var(--ink);flex:1}
.price-row .w{font-size:12px;color:var(--muted);white-space:nowrap}
.pane-pricing .pane-foot{margin-top:8px}
.btn-sm{display:inline-flex;align-items:center;gap:4px;height:32px;
  padding:0 8px 0 14px;border-radius:8px;background:var(--acc);color:#fff;
  font-size:13px;font-weight:600;transition:background .2s}
.btn-sm:hover{background:var(--ink);color:#fff;text-decoration:none}
/* .pane-foot a (0,2,1) outranks .btn-sm (0,1,0) and painted the label ink-on-
   indigo at 3.31:1. Measured, not guessed - a class next to a descendant
   selector loses quietly. */
.pane-foot a.btn-sm{color:#fff}
.btn-sm svg{width:14px;height:14px}

/* ---- right-hand group -------------------------------------------- */
.nav-right{margin-left:auto;display:flex;align-items:center;gap:10px}
.cta{display:inline-flex;align-items:center;white-space:nowrap;gap:4px;
  height:40px;padding:0 12px 0 16px;border-radius:6px;background:var(--acc);
  color:#fff;font-size:14px;font-weight:600;transition:background .2s}
.cta:hover{background:var(--ink);color:#fff;text-decoration:none}
.cta svg{width:16px;height:16px}
.cta[aria-current="page"]{background:var(--ink)}
.burger{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;
  color:var(--ink);border:1px solid rgba(10,37,64,.14)}
.burger svg{width:20px;height:20px}
.burger .ico-x{display:none}
.burger[aria-expanded="true"] .ico-x{display:block}
.burger[aria-expanded="true"] .ico-burger{display:none}

/* The six labels + the lockup + the CTA need room. Measured in Chromium:
   lockup 166 + nav 599 + CTA 98 + 2x18 gap + 2x40 padding = 979px, so at
   960-1179 the "/ Kind" suffix has to go and the nav has to tighten - exactly
   the band in which the export drops DE/EN (showLangInNav). Without this the
   document scrolls sideways by 29px at 1000px wide. */
@media (min-width:960px) and (max-width:1179px){
  .lockup .sep,.lockup .kind{display:none}
.nav-list{gap:2px;margin-left:4px}
.nav-item{padding:8px 10px}
}

/* ---- breakpoint: isDesktop = vw >= 960 in the export -------------- */
@media (max-width:959px){
  .nav-list,.nav-panel,.nav-caret,.nav-right .cta{display:none}
.lockup .kind,.lockup .sep{display:none}
}
@media (min-width:960px){ .burger{display:none} }

/* ---- mobile drawer ----------------------------------------------- */
.drawer{position:fixed;inset:0;z-index:70;background:#fff;overflow-y:auto;
  padding:88px clamp(20px,5vw,48px) 40px;animation:fadeIn .25s ease}
.drawer[hidden]{display:none}
.dgroup{padding:14px 0;border-bottom:1px solid rgba(10,37,64,.08)}
.dgroup > .t{font-size:13px;font-weight:600;color:var(--acc-text)}
.dgroup .links{display:grid;margin-top:6px}
.dgroup a{display:flex;justify-content:space-between;align-items:center;
  gap:12px;padding:10px 0;font-size:18px;font-weight:600;color:var(--ink);
  text-align:left}
.dgroup a:hover{text-decoration:none;color:var(--acc-text)}
.dgroup a svg{width:16px;height:16px;color:#8898AA;flex:none}
.dgroup a[aria-current="page"]{color:var(--acc-text)}
.drawer .cta{display:flex;justify-content:center;width:100%;height:48px;
  margin-top:24px;border-radius:8px;font-size:15px;padding:0}
.drawer .lang{margin:22px auto 0;width:max-content}

/* =====================================================================
   FOOTER
   The start page footer is background:transparent with an absolutely
   positioned #0A1F44 layer at z-index:-2, because a WebGL canvas sits at
   z-index:-1 behind the whole page. On a page without that canvas the
   z-index:-2 layer paints BEHIND the document background and the footer
   comes out white. So: paint the ground directly.
   ===================================================================== */
.site-foot{background:var(--navy);color:var(--navy-ink);
  margin-top:clamp(64px,8vw,110px)}
.site-foot .inner{max-width:1440px;margin:0 auto;
  padding:48px clamp(20px,4vw,48px) 36px;
  border-left:1px solid rgba(255,255,255,.08);
  border-right:1px solid rgba(255,255,255,.08);
  border-top:1px solid rgba(255,255,255,.08)}
.fcols{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));
  gap:32px 24px}
.fcol h2{font-size:14px;font-weight:600;color:#fff;margin:0 0 12px}
.fcol ul{list-style:none;padding:0;margin:0}
.fcol a{display:block;font-size:14px;color:var(--navy-ink);padding:5px 0;
  transition:color .2s}
.fcol a:hover{color:#fff;text-decoration:none}
.fcol a[aria-current="page"]{color:#fff;font-weight:600}
.fbot{display:flex;flex-wrap:wrap;justify-content:space-between;align-items:center;
  gap:16px;margin-top:48px;padding-top:24px;
  border-top:1px solid rgba(255,255,255,.1);font-size:13px;color:var(--navy-mut)}
/* Without this the global a{color:var(--acc-text)}
paints #4D47C7 on #0A1F44 -
   a 1.9:1 contrast ratio. Measured; see chrome.md. */
.fbot a{color:var(--navy-ink)}
.fbot a:hover{color:#fff}
.fbot .id{display:flex;align-items:center;gap:11px}
.fbot .id svg{display:block;width:28px;height:28px}
.fbot .meta{display:flex;align-items:center;gap:14px;flex-wrap:wrap}
.fbot .brand{display:inline-flex;align-items:center;gap:6px;color:var(--navy-ink);
  font-weight:600}
.fbot .brand:hover{color:#fff;text-decoration:none}
.fbot .brand svg{width:14px;height:14px}
.fbot .lang{border-color:rgba(255,255,255,.18)}
.fbot .lang a,.fbot .lang span{color:var(--navy-mut)}
.fbot .lang [aria-current]{background:rgba(255,255,255,.14);color:#fff}
.fbot .lang a:hover{color:#fff}

/* =====================================================================
   "Die Seite fragen" PILL
   ===================================================================== */
.dock{position:fixed;right:20px;bottom:20px;z-index:60;display:flex;
  flex-direction:column;align-items:flex-end;gap:10px;
  opacity:0;visibility:hidden;transform:translateY(10px);
  transition:opacity .3s,transform .3s var(--ease),visibility 0s .3s}
.dock[data-show="true"]{opacity:1;visibility:visible;transform:none;
  transition-delay:0s}
@media (max-width:599px){.dock{display:none}}   /* dockShow requires vw >= 600 */
.dock-btn{display:inline-flex;align-items:center;gap:10px;height:48px;
  padding:0 18px 0 12px;border-radius:999px;background:var(--navy);color:#fff;
  font-size:14px;font-weight:600;
  box-shadow:0 20px 50px -20px rgba(0,0,0,.6),0 0 0 1px rgba(255,255,255,.12);
  transition:transform .2s,box-shadow .2s}
.dock-btn:hover{transform:translateY(-2px);
  box-shadow:0 24px 60px -20px rgba(0,0,0,.7),0 0 0 1px rgba(159,153,255,.5)}
.dock-btn svg{display:block;flex:none;width:26px;height:26px}
.dock-panel{width:min(380px,calc(100vw - 40px));background:var(--dock);
  color:#EEF1FA;border:1px solid rgba(255,255,255,.10);border-radius:14px;
  box-shadow:0 40px 100px -30px rgba(0,0,0,.7);overflow:hidden;
  animation:fadeUp .35s var(--ease)}
.dock-panel[hidden]{display:none}
.dock-head{display:flex;align-items:center;gap:10px;padding:12px 14px;
  border-bottom:1px solid rgba(255,255,255,.08)}
.dock-head svg.mk{width:26px;height:26px;flex:none}
.dock-head .t{font-weight:600;font-size:14px}
.dock-head .src{margin-left:auto;font-family:'JetBrains Mono',ui-monospace,monospace;
  font-size:11px;color:var(--navy-mut)}
.dock-close{width:30px;height:30px;border-radius:8px;display:grid;
  place-items:center;color:var(--navy-ink);transition:background .2s}
.dock-close:hover{background:rgba(255,255,255,.08);color:#fff}
.dock-close svg{width:16px;height:16px}
.dock-list{height:min(320px,45vh);overflow-y:auto;padding:14px;display:flex;
  flex-direction:column;gap:12px}
.dock-list .intro{font-size:13.5px;line-height:1.55;color:var(--navy-ink)}
.msg-u{align-self:flex-end;max-width:88%;background:rgba(255,255,255,.10);
  color:#fff;border-radius:12px 12px 3px 12px;padding:8px 12px;font-size:13.5px;
  line-height:1.5}
.msg-b{display:flex;gap:10px;align-items:flex-start;max-width:94%}
.msg-b svg{width:22px;height:22px;flex:none}
.msg-b p{font-size:13.5px;line-height:1.55;color:#EEF1FA;white-space:pre-wrap;
  margin:0}
.dock-chips{display:flex;gap:6px;padding:0 14px 10px;flex-wrap:wrap}
.dock-chips button{font-size:11.5px;font-weight:500;padding:5px 10px;
  border-radius:999px;border:1px solid rgba(255,255,255,.14);
  color:var(--navy-ink);transition:border-color .2s,color .2s}
.dock-chips button:hover{border-color:rgba(255,255,255,.4);color:#fff}
.dock-form{display:flex;gap:8px;padding:12px 14px 14px;
  border-top:1px solid rgba(255,255,255,.08)}
.dock-form .ring{flex:1;min-width:0;display:flex;border-radius:9px;padding:1.5px;
  background:linear-gradient(90deg,#FFB46B,#FF5A8C,#C05CFF,#5FC3FF,#FFB46B);
  background-size:300% 100%;animation:streamBorder 7s linear infinite}
.dock-form input{flex:1;min-width:0;height:41px;padding:0 16px;border-radius:7.5px;
  border:0;background:var(--dock-in);color:#fff;font-size:14px;outline:none;
  transition:background .2s}
.dock-form input:focus{background:#132C66}
.dock-form button{flex:none;height:44px;padding:0 14px;border-radius:8px;
  background:var(--acc);color:#fff;font-size:14px;font-weight:600;
  transition:background .2s}
.dock-form button:hover{background:#7A73FF}

/* ------------------------------------------------------------ keyframes
   Verbatim from the export's <helmet> block. */
@keyframes fadeUp{from{opacity:0;transform:translateY(14px)}
to{opacity:1;transform:none}}
@keyframes fadeIn{from{opacity:0}
to{opacity:1}}
@keyframes flowA{0%{transform:translate3d(-7%,-5%,0) scale(1.1)}50%{transform:translate3d(7%,6%,0) scale(1.3)}100%{transform:translate3d(-7%,-5%,0) scale(1.1)}}
@keyframes flowB{0%{transform:translate3d(6%,7%,0) scale(1.25)}50%{transform:translate3d(-7%,-6%,0) scale(1.05)}100%{transform:translate3d(6%,7%,0) scale(1.25)}}
@keyframes pulseDot{0%,100%{box-shadow:0 0 0 0 rgba(21,190,83,.55)}70%{box-shadow:0 0 0 7px rgba(21,190,83,0)}}
@keyframes streamBorder{to{background-position:300% 0}}
@keyframes tileIn{from{opacity:0;transform:scale(.88)}
to{opacity:1;transform:none}}
.lockup .mark{animation:tileIn .6s var(--ease) both}
@media (prefers-reduced-motion:reduce){
  *,*::before,*::after{animation-duration:.01ms!important;
    animation-iteration-count:1!important;transition-duration:.01ms!important}
html{scroll-behavior:auto}
}

/* --- demo page only, not part of the chrome ----------------------- */
.demo{max-width:760px;margin:0 auto;padding:56px clamp(20px,4vw,48px) 0}"""

SPRITE = """<svg class="sprite" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg">
  <!-- lifted from brand/mccain-icons.svg -->
  <symbol id="i-chev-down" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></symbol>
  <symbol id="i-chev-right" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></symbol>
  <symbol id="i-x" viewBox="0 0 24 24"><path d="M18 6 6 18M6 6l12 12" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></symbol>
  <symbol id="i-arrow-ur" viewBox="0 0 24 24"><path d="M7 17 17 7M7 7h10v10" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></symbol>
  <!-- Component.ICONS, drawn at stroke-width 1.75 like the export's icon() -->
  <symbol id="i-sparkles" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9z"/><path d="M19 17v4"/><path d="M17 19h4"/></g></symbol>
  <symbol id="i-layout" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M3 5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M3 9h18"/><path d="M9 21V9"/></g></symbol>
  <symbol id="i-globe" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20z"/><path d="M2 12h20"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></g></symbol>
  <symbol id="i-server" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1z"/><path d="M4 14h16a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1z"/><path d="M7 7h.01"/><path d="M7 17h.01"/></g></symbol>
  <symbol id="i-book" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 7v14"/><path d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z"/></g></symbol>
  <symbol id="i-file" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/></g></symbol>
  <symbol id="i-layers" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z"/><path d="M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"/><path d="M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"/></g></symbol>
  <symbol id="i-commit" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path d="M3 12h6"/><path d="M15 12h6"/></g></symbol>
  <symbol id="i-gauge" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="m12 14 4-4"/><path d="M3.34 19a10 10 0 1 1 17.32 0"/></g></symbol>
</svg>"""


def header(*, r, kind, current="", section=""):
    """current: the path of this page, so its entry carries aria-current.
    section: which top-level menu this page belongs under (visual marker only -
    aria-current="page" on a menu BUTTON would claim the button is the page)."""
    html = HEADER.format(r=r)
    if current:
        html = html.replace('href="%s%s"' % (r, current),
                            'href="%s%s" aria-current="page"' % (r, current), 1)
    if section:
        html = html.replace('data-menu="%s"' % section,
                            'data-menu="%s" data-section-current="true"' % section, 1)
    return html.replace("<span class=\"kind\"></span>",
                        "<span class=\"kind\">%s</span>" % kind)


def drawer(*, r, current=""):
    html = DRAWER.format(r=r)
    if current:
        html = html.replace('href="%s%s"' % (r, current),
                            'href="%s%s" aria-current="page"' % (r, current), 1)
    return html


def footer(*, r, current=""):
    html = FOOTER.format(r=r)
    if current:
        html = html.replace('href="%s%s"' % (r, current),
                            'href="%s%s" aria-current="page"' % (r, current), 1)
    return html


def pill(*, r):
    return PILL.format(r=r)


HEADER = """<header class="site-head" data-chrome-header data-scrolled="false">
  <div class="nav-inner" data-nav-inner>

    <a class="lockup" href="{r}index.html">
      <img class="mark" src="{r}brand/mccain-mark-free-color.svg" width="28" height="28" alt="">
      <span class="word">mccain digital</span>
      <span class="sep" aria-hidden="true">/</span>
      <span class="kind"></span>
    </a>

    <nav class="nav-list" data-nav-list data-open="false" aria-label="Hauptnavigation">
      <span class="nav-ind" data-nav-ind aria-hidden="true"></span>

      <button class="nav-item" type="button" id="nt-services" data-menu="services"
              aria-expanded="false" aria-controls="np-services">
        Leistungen<svg class="chev" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-down"></use></svg>
      </button>
      <button class="nav-item" type="button" id="nt-work" data-menu="work"
              aria-expanded="false" aria-controls="np-work">
        Arbeiten<svg class="chev" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-down"></use></svg>
      </button>
      <button class="nav-item" type="button" id="nt-studio" data-menu="studio"
              aria-expanded="false" aria-controls="np-studio">
        Studio<svg class="chev" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-down"></use></svg>
      </button>
      <button class="nav-item" type="button" id="nt-process" data-menu="process"
              aria-expanded="false" aria-controls="np-process">
        Ablauf<svg class="chev" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-down"></use></svg>
      </button>
      <button class="nav-item" type="button" id="nt-resources" data-menu="resources"
              aria-expanded="false" aria-controls="np-resources">
        Ressourcen<svg class="chev" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-down"></use></svg>
      </button>
      <button class="nav-item" type="button" id="nt-pricing" data-menu="pricing"
              aria-expanded="false" aria-controls="np-pricing">
        Preise<svg class="chev" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-down"></use></svg>
      </button>
    </nav>

    <!-- Caret + panel sit here, directly after the <nav>, so Tab from the
         last trigger lands INSIDE the open panel. The export puts them after
         the right-hand group, which makes Tab jump over DE/EN and Kontakt
         first. Same pixels, better order. -->
    <div class="nav-caret" data-nav-caret aria-hidden="true"></div>

    <div class="nav-panel" data-nav-panel data-open="false">

      <!-- ---------------------------------------------- Leistungen -->
      <div class="pane pane-services" id="np-services" data-pane="services"
           role="group" aria-labelledby="nt-services">
        <div class="pane-grid">
          <a class="mi" href="{r}services/ai-tools.html">
            <span class="ic ic-ai"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-sparkles"></use></svg></span>
            <span class="tx"><span class="t">KI-Tools</span>
              <span class="d">RAG, Agenten, MCP-Server &ndash; auf Ihren Daten</span></span>
          </a>
          <a class="mi" href="{r}services/web-apps.html">
            <span class="ic ic-apps"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-layout"></use></svg></span>
            <span class="tx"><span class="t">Web-Apps</span>
              <span class="d">React, Next.js, TypeScript &ndash; vom MVP bis zur Skalierung</span></span>
          </a>
          <a class="mi" href="{r}services/websites.html">
            <span class="ic ic-web"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-globe"></use></svg></span>
            <span class="tx"><span class="t">Websites</span>
              <span class="d">Handgebaut, Lighthouse 100, lesbar f&uuml;r Mensch und KI</span></span>
          </a>
          <a class="mi" href="{r}services/software.html">
            <span class="ic ic-software"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-server"></use></svg></span>
            <span class="tx"><span class="t">Software f&uuml;r Unternehmen</span>
              <span class="d">Dashboards, interne Tools, Integrationen &ndash; Cloud oder on-premise</span></span>
          </a>
          <a class="promo" href="{r}index.html#ai">
            <span class="flow" aria-hidden="true"><i class="a"></i><i class="b"></i></span>
            <span class="veil" aria-hidden="true"></span>
            <span class="live"><span class="dot" aria-hidden="true"></span>Live &middot; Claude</span>
            <span class="h">Fragen Sie diese Seite.</span>
            <span class="s">Die Seite fragen &rsaquo;</span>
          </a>
        </div>
        <div class="pane-foot">
          <span class="note">Nicht sicher, was passt?</span>
          <span style="display:flex;gap:18px">
            <a class="acc" href="{r}index.html#ai">Die Seite fragen &rsaquo;</a>
            <a href="{r}index.html#process">Ablauf ansehen &rsaquo;</a>
          </span>
        </div>
      </div>

      <!-- ------------------------------------------------- Arbeiten -->
      <div class="pane pane-work" id="np-work" data-pane="work"
           role="group" aria-labelledby="nt-work">
        <div class="pane-grid">
          <a class="mi" href="{r}index.html#work">
            <span class="ic ic-case-recall"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-commit"></use></svg></span>
            <span class="tx"><span class="t">whatever-recall<span class="badge">Live</span></span>
              <span class="d">KI-natives Projektged&auml;chtnis &ndash; live, self-hosted</span></span>
          </a>
          <a class="mi" href="{r}index.html#work">
            <span class="ic ic-case-site"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-gauge"></use></svg></span>
            <span class="tx"><span class="t">mccain-digital.com<span class="badge">Live</span></span>
              <span class="d">Handgeschrieben, 100/100/100/100 in Lighthouse</span></span>
          </a>
        </div>
        <div class="pane-foot">
          <span class="note">Kundenprojekte folgen nach Freigabe.</span>
          <a href="{r}index.html#work">Alle Projekte &rsaquo;</a>
        </div>
      </div>

      <!-- --------------------------------------------------- Studio -->
      <div class="pane pane-studio" id="np-studio" data-pane="studio"
           role="group" aria-labelledby="nt-studio">
        <div class="pane-grid">
          <a class="studio-card" href="{r}index.html#studio">
            <span class="k">Das Studio</span>
            <span class="y">2016 &rarr;</span>
            <span class="p">Unabh&auml;ngig seit 2016. Zwei Senior-Gr&uuml;nder, keine Junioren,
              keine Account-Manager.</span>
          </a>
          <div class="stack">
            <span class="lbl">Team</span>
            <a class="person" href="{r}index.html#studio">
              <span class="av" style="background:linear-gradient(135deg,#5FC3FF,#6E7BFF)">C</span>
              <span><span class="n">Christian</span>
                <span class="r">Mitgr&uuml;nder &middot; Entwicklung &amp; Betrieb</span></span>
            </a>
            <a class="person" href="{r}index.html#studio">
              <span class="av" style="background:linear-gradient(135deg,#C05CFF,#FF5A8C)">K</span>
              <span><span class="n">Kathi</span>
                <span class="r">Mitgr&uuml;nderin &middot; Design &amp; Marke</span></span>
            </a>
          </div>
        </div>
        <div class="pane-foot">
          <span class="note">Kosten, Dauer, Zust&auml;ndigkeiten.</span>
          <a href="{r}index.html#faq">Fragen &amp; Antworten &rsaquo;</a>
        </div>
      </div>

      <!-- --------------------------------------------------- Ablauf -->
      <div class="pane pane-process" id="np-process" data-pane="process"
           role="group" aria-labelledby="nt-process">
        <div class="pane-grid">
          <a class="step" href="{r}index.html#process"><span class="n">01</span>
            <span><span class="hd"><span class="t">Eine pers&ouml;nliche Antwort</span>
              <span class="w">innerhalb von 24 Stunden</span></span>
              <span class="d">Von Christian oder Kathi, zu Ihrem konkreten Vorhaben.</span></span></a>
          <a class="step" href="{r}index.html#process"><span class="n">02</span>
            <span><span class="hd"><span class="t">Ein Gespr&auml;ch</span>
              <span class="w">30&ndash;45 Minuten</span></span>
              <span class="d">Telefon oder Video &ndash; &uuml;ber Ihr Ziel, nicht &uuml;ber unseren Prozess.</span></span></a>
          <a class="step" href="{r}index.html#process"><span class="n">03</span>
            <span><span class="hd"><span class="t">Ein Festpreis</span>
              <span class="w">innerhalb von 48 Stunden</span></span>
              <span class="d">Eine konkrete Zahl mit klar definiertem Umfang.</span></span></a>
          <a class="step" href="{r}index.html#process"><span class="n">04</span>
            <span><span class="hd"><span class="t">Etwas Klickbares</span>
              <span class="w">Woche eins</span></span>
              <span class="d">Echte Screens in Woche eins, danach jede Woche eine Demo.</span></span></a>
        </div>
        <div class="pane-foot">
          <span class="note">Sie k&ouml;nnen nach jedem Schritt aufh&ouml;ren.</span>
          <a class="acc" href="{r}kontakt.html">Anfrage starten &rsaquo;</a>
        </div>
      </div>

      <!-- ----------------------------------------------- Ressourcen -->
      <div class="pane pane-resources" id="np-resources" data-pane="resources"
           role="group" aria-labelledby="nt-resources">
        <div class="pane-grid">
          <!-- "Tech-Notizen" is NOT here on purpose: on the start page it is
               href="#" + preventDefault (dc.html:1081), a link that goes
               nowhere. A subpage should not ship one. -->
          <a class="mi" href="{r}llms.txt">
            <span class="ic ic-res"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-file"></use></svg></span>
            <span class="tx"><span class="t">llms.txt &amp; KI-Lesbarkeit</span>
              <span class="d">Wie diese Seite von KI-Agenten gelesen wird &ndash; und warum das z&auml;hlt.</span></span>
          </a>
          <a class="mi" href="{r}index.html#stack">
            <span class="ic ic-res"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-layers"></use></svg></span>
            <span class="tx"><span class="t">Stack &amp; Werkzeuge</span>
              <span class="d">Womit wir bauen, und warum.</span></span>
          </a>
          <a class="mi" href="{r}brand-guide.html">
            <span class="ic ic-res"><svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-book"></use></svg></span>
            <span class="tx"><span class="t">Marke &amp; Downloads</span>
              <span class="d">Logo, Farben, Typografie &ndash; als Dateien zum Mitnehmen.</span></span>
          </a>
        </div>
      </div>

      <!-- ---------------------------------------------------- Preise -->
      <div class="pane pane-pricing" id="np-pricing" data-pane="pricing"
           role="group" aria-labelledby="nt-pricing">
        <div class="price-head">
          <div class="k">Preise</div>
          <div class="t">Der Weg zum Festpreis</div>
          <p>Keine Preisliste. Jedes Angebot ist eine konkrete Zahl mit klar
             definiertem Umfang.</p>
          <div style="margin-top:14px">
            <div class="price-row"><span class="n">01</span>
              <span class="t">Eine pers&ouml;nliche Antwort</span>
              <span class="w">innerhalb von 24 Stunden</span></div>
            <div class="price-row"><span class="n">02</span>
              <span class="t">Ein Gespr&auml;ch</span>
              <span class="w">30&ndash;45 Minuten</span></div>
            <div class="price-row"><span class="n">03</span>
              <span class="t">Ein Festpreis</span>
              <span class="w">innerhalb von 48 Stunden</span></div>
          </div>
        </div>
        <div class="pane-foot">
          <span class="note">Bis zum Angebot kostet Sie nichts etwas.</span>
          <a class="btn-sm" href="{r}kontakt.html">Anfrage starten<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
        </div>
      </div>

    </div><!-- /.nav-panel -->

    <div class="nav-right">
      <!-- DE/EN: present here ONLY to show the control. It must NOT ship on a
           subpage until build_pages.py emits English pages - see chrome.md,
           section "DE/EN". On the start page it is a state toggle
           (localStorage 'mcd.lang'); a static page cannot honour that. -->

      <a class="cta" href="{r}kontakt.html">Kontakt<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>

      <button class="burger" type="button" data-burger aria-expanded="false"
              aria-controls="mcd-drawer" aria-label="Men&uuml;">
        <svg class="ico-burger" viewBox="0 0 24 24" fill="none" stroke="currentColor"
             stroke-width="1.75" stroke-linecap="round" aria-hidden="true">
          <path d="M4 7h16"></path><path d="M4 12h16"></path><path d="M4 17h16"></path>
        </svg>
        <svg class="ico-x" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-x"></use></svg>
      </button>
    </div>

  </div><!-- /.nav-inner -->
</header>"""

DRAWER = """<div class="drawer" id="mcd-drawer" data-drawer hidden>
  <div class="dgroup">
    <div class="t">Leistungen</div>
    <div class="links">
      <a href="{r}services/ai-tools.html">KI-Tools<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}services/web-apps.html">Web-Apps<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}services/websites.html">Websites<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}services/software.html">Software f&uuml;r Unternehmen<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
    </div>
  </div>
  <div class="dgroup">
    <div class="t">Arbeiten</div>
    <div class="links">
      <a href="{r}index.html#work">whatever-recall<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}index.html#work">mccain-digital.com<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
    </div>
  </div>
  <div class="dgroup">
    <div class="t">Studio</div>
    <div class="links">
      <a href="{r}index.html#studio">Team<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}index.html#faq">Fragen &amp; Antworten<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
    </div>
  </div>
  <div class="dgroup">
    <div class="t">Ablauf</div>
    <div class="links">
      <a href="{r}index.html#process">01 &middot; Eine pers&ouml;nliche Antwort<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}index.html#process">02 &middot; Ein Gespr&auml;ch<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}index.html#process">03 &middot; Ein Festpreis<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}index.html#process">04 &middot; Etwas Klickbares<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
    </div>
  </div>
  <div class="dgroup">
    <div class="t">Ressourcen</div>
    <div class="links">
      <a href="{r}llms.txt">llms.txt &amp; KI-Lesbarkeit<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}index.html#stack">Stack &amp; Werkzeuge<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
      <a href="{r}brand-guide.html">Marke &amp; Downloads<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
    </div>
  </div>
  <div class="dgroup">
    <div class="t">Preise</div>
    <div class="links">
      <a href="{r}index.html#process">Der Weg zum Festpreis<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
    </div>
  </div>
  <a class="cta" href="{r}kontakt.html">Kontakt<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chev-right"></use></svg></a>
</div>"""

FOOTER = """<footer class="site-foot">
  <div class="inner">
    <div class="fcols">
      <div class="fcol">
        <h2>Leistungen</h2>
        <ul>
          <li><a href="{r}services/ai-tools.html">KI-Tools</a></li>
          <li><a href="{r}services/web-apps.html">Web-Apps</a></li>
          <li><a href="{r}services/websites.html">Websites</a></li>
          <li><a href="{r}services/software.html">Software f&uuml;r Unternehmen</a></li>
        </ul>
      </div>
      <div class="fcol">
        <h2>Arbeiten</h2>
        <ul>
          <li><a href="{r}index.html#work">whatever-recall</a></li>
          <li><a href="{r}index.html#work">mccain-digital.com</a></li>
        </ul>
      </div>
      <div class="fcol">
        <h2>Studio</h2>
        <ul>
          <li><a href="{r}index.html#studio">Team</a></li>
          <li><a href="{r}index.html#process">Ablauf</a></li>
          <li><a href="{r}index.html#faq">Fragen &amp; Antworten</a></li>
          <li><a href="{r}kontakt.html">Kontakt</a></li>
        </ul>
      </div>
      <div class="fcol">
        <h2>Ressourcen</h2>
        <ul>
          <li><a href="{r}brand-guide.html">Marke &amp; Downloads</a></li>
          <li><a href="{r}llms.txt">llms.txt &amp; KI-Lesbarkeit</a></li>
          <li><a href="{r}index.html#stack">Stack &amp; Werkzeuge</a></li>
        </ul>
      </div>
      <div class="fcol">
        <h2>Rechtliches</h2>
        <ul>
          <li><a href="{r}legal/imprint.html">Impressum</a></li>
          <li><a href="{r}legal/privacy.html">Datenschutz</a></li>
          <li><a href="{r}legal/terms.html">AGB</a></li>
          <li><a href="{r}legal/withdrawal.html">Widerruf</a></li>
        </ul>
      </div>
    </div>

    <div class="fbot">
      <div class="id">
        <img src="{r}brand/mccain-mark-free-color.svg" width="28" height="28" alt="">
        <span>&copy; 2026 McCain Digital &middot; Oberostendorf, Bayern</span>
      </div>
      <div class="meta">
        <a class="brand" href="{r}brand-guide.html">Marke &amp; Downloads<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-arrow-ur"></use></svg></a>
        <span>Gebaut von den zwei Personen, die es anbieten.</span>
        <a href="mailto:info@mccain-digital.com">info@mccain-digital.com</a>
        <a href="tel:+491705922203">+49&nbsp;170&nbsp;59&nbsp;222&nbsp;03</a>
      </div>
    </div>
  </div>
</footer>"""

PILL = """<div class="dock" data-dock data-show="false">

  <div class="dock-panel" data-dock-panel id="mcd-ask" hidden>
    <div class="dock-head">
      <img class="mk" src="{r}brand/mccain-mark-free-color.svg" width="28" height="28" alt="">
      <span class="t">Fragen</span>
      <!-- The start page prints "claude-haiku-4-5" here. On a static page no
           model answers - say what actually answers. -->
      <span class="src">Wissensbasis</span>
      <button class="dock-close" type="button" data-dock-close aria-label="Schlie&szlig;en">
        <svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-x"></use></svg>
      </button>
    </div>

    <div class="dock-list" data-dock-list role="log" aria-live="polite" aria-label="Antworten">
      <p class="intro">Fragen Sie mich zu Kosten, Dauer oder Vorgehen &ndash; oder
         beschreiben Sie Ihr Vorhaben in einer Zeile.</p>
    </div>

    <div class="dock-chips" data-dock-chips>
      <button type="button">Was kostet ein Projekt?</button>
      <button type="button">Wie lange dauert eine Web-App?</button>
      <button type="button">Wer baut das konkret?</button>
      <button type="button">K&ouml;nnen wir selbst hosten?</button>
    </div>

    <form class="dock-form" data-dock-form>
      <span class="ring">
        <input type="text" maxlength="500" placeholder="Ihre Frage &hellip;"
               aria-label="Ihre Frage" data-dock-input>
      </span>
      <button type="submit">Senden</button>
    </form>
  </div>

  <button class="dock-btn" type="button" data-dock-toggle aria-expanded="false"
          aria-controls="mcd-ask">
    <img src="{r}brand/mccain-mark-free-color.svg" width="28" height="28" alt="">
    <span data-dock-label>Die Seite fragen</span>
  </button>
</div>"""
