/* ============================================================
   McCain Digital — the shared page runtime.

   Everything EVERY page needs: the webfont hand-off to the pixel
   engine, the theme switch, the nav, magnetic buttons, the velocity
   marquee, the tooltip card and the pixel boot.

   Page-specific widgets live in the page's own script (v3.js for the
   home page, svc.js for the service pages). This file must load right
   after data.js and BEFORE those, because it publishes window.MCDUI.

   Nothing in here assumes an element exists — a page that has no
   marquee simply gets no marquee.
   ============================================================ */
(() => {
  "use strict";

  const d = document;
  const root = d.documentElement;
  const reduced = matchMedia("(prefers-reduced-motion: reduce)").matches;
  const fine = matchMedia("(hover: hover) and (pointer: fine)").matches;

  // pages below the root set data-root=".." on <html>; same contract as menu.js
  const ROOT = root.dataset.root || ".";

  /* ============================================================
     1) WEBFONT → PIXEL ENGINE
     The rasterizer draws through an SVG foreignObject, which cannot
     reach document fonts. Embed the face as a data-URI so pixel
     headlines are built from the REAL typeface, not the fallback.
     ============================================================ */
  function embedFont() {
    return fetch(ROOT + "/fonts/schibsted-normal-latin.woff2")
      .then((r) => (r.ok ? r.arrayBuffer() : Promise.reject(new Error("font"))))
      .then((buf) => {
        const bytes = new Uint8Array(buf);
        let bin = "";
        for (let i = 0; i < bytes.length; i += 1) bin += String.fromCharCode(bytes[i]);
        window.PixelFXFontCSS =
          '@font-face{font-family:"Schibsted Grotesk";font-weight:100 900;src:url(data:font/woff2;base64,' +
          btoa(bin) + ') format("woff2")}';
      })
      .catch(() => { /* fall back to the system face — effect still works */ });
  }

  /* ============================================================
     2) THEME
     ============================================================ */
  let pixelHosts = [];
  const themeBtn = d.getElementById("themeT");

  /* Every page also applies this inline in <head>, before the stylesheet
     resolves - that is what stops the dark flash AND stops a pixel headline
     from rasterizing the outgoing theme's colour mid-transition. This stays as
     the fallback for any page that ever ships without the snippet; assigning
     the value it already has costs nothing and starts no transition. */
  try {
    const saved = localStorage.getItem("mcd-v3-theme");
    if (saved === "light" || saved === "dark") root.dataset.theme = saved;
  } catch { /* private mode — keep the default */ }

  /* ---------- the travelling rim's palette ----------

     One list on :root, because everything that wears the rim is wearing the
     same effect - the console in section 01 and the same console once it has
     docked at the page edge. Generated by the pixel engine rather than written
     out here: a second copy of a colour list is already the wrong one the next
     time the accent moves.

     It is built from --acc, the logo yellow, and NOT from --acc-text. The two
     differ on purpose: --acc-text darkens to #806400 so accent TEXT can be
     read on paper. Feeding that to the rim made the border visibly muddy in
     light mode - for no gain, because the console sits on the same ink band in
     both themes, and because a 1.5px decorative border is not text and has no
     contrast bar to clear. The logo yellow is also the one colour on this site
     that is never re-tinted, which is exactly the right source for an effect
     that should look the same wherever it appears.

     No ground is passed for the same reason: the legibility clamp inside
     wavePalette exists to keep TEXT readable, and clamping a border to a
     background it does not sit on only takes the colour out of it.

     Regenerated on a theme switch anyway. It costs one call and it is what
     keeps this honest if --acc ever becomes theme-dependent. */
  function paintRimPalette() {
    const cs = getComputedStyle(root);
    const period = parseFloat(cs.getPropertyValue("--rim-period")) || 480;
    const angle = parseFloat(cs.getPropertyValue("--rim-angle")) || 112;

    /* The COLOURS are no longer generated here. They used to come from
       PixelFX.wavePalette("rainbow"), and a full spectrum was the loudest
       thing on a page whose whole argument is that one accent punctuates a
       restrained system. They are --wave-stops in v3.css now, where they can
       be read and argued with: the logo yellow travelling through the green
       and back, over the same period.

       What still has to be COMPUTED is the geometry. A horizontal move of dX
       advances an angled gradient by dX * sin(angle) along its line, so the
       move that covers exactly one period is period / sin(angle) - and
       getting that wrong is what made the border visibly restart every
       cycle. Computed here so the angle is written in exactly one place. */
    root.style.setProperty("--rim-shift",
      (period / Math.sin(angle * Math.PI / 180)).toFixed(2) + "px");

    paintWaveText(cs);
  }

  /* THE WAVE AS A TEXT COLOUR.

     The console's rim is the one place on the page where the accent is not a
     flat colour but a journey - yellow through the green and back - and the
     owner asked for that journey on the studio band's type. It cannot be
     painted there at its own brightness: #f5c518 on paper is 1.48:1.

     So each stop keeps its hue and gives up only its lightness, which is the
     rule the rest of the system already follows (--acc for fills, --acc-ink
     for text). The engine's legible() does exactly that and moves in
     whichever direction the ground demands, so this same call produces the
     untouched stops on an ink band and a deep gold-to-olive on paper.

     Per element rather than per theme: the ground that matters is the BAND's
     background, and a paper band stays paper in either theme. */
  function paintWaveText(cs) {
    const hosts = d.querySelectorAll("[data-wavetext]");
    if (!hosts.length || !window.PixelFX || !PixelFX.legibleStops) return;
    const raw = (cs || getComputedStyle(root)).getPropertyValue("--wave-stops");
    // "#f5c518 0px, #d9c40f 96px, ..." -> colours and their positions
    const parts = raw.split(",").map((s) => s.trim()).filter(Boolean);
    const cols = [], pos = [];
    parts.forEach((p) => {
      const m = p.match(/^(\S+)\s+(\S+)$/);
      if (m) { cols.push(m[1]); pos.push(m[2]); }
    });
    if (!cols.length) return;
    hosts.forEach((el) => {
      const ground = PixelFX.tokenRGB(el, "--bg", "#f2f2ef");
      const fixed = PixelFX.legibleStops(cols, ground, 5.2);
      el.style.setProperty("--wave-stops-text",
        fixed.map((cc, i) => cc + " " + pos[i]).join(", "));
    });
  }
  paintRimPalette();

  /* Off screen it stops. The dock's rim only exists while the dock is on
     screen, but the console's sits in the page and would otherwise animate a
     blurred layer through the whole scroll for nobody. A paused CSS animation
     resumes where it stopped, so coming back is not a jump. */
  if (!reduced && "IntersectionObserver" in window) {
    const rimIO = new IntersectionObserver((es) => {
      es.forEach((e) => e.target.classList.toggle("is-still", !e.isIntersecting));
    }, { rootMargin: "120px" });
    d.querySelectorAll(".rim-hold").forEach((el) => rimIO.observe(el));
  }

  if (themeBtn) {
    let themeRedraw = null;
    themeBtn.addEventListener("click", () => {
      const next = root.dataset.theme === "dark" ? "light" : "dark";
      root.dataset.theme = next;
      try { localStorage.setItem("mcd-v3-theme", next); } catch { /* ignore */ }

      // The pixel fields hold the OLD colours and have to be re-sampled — but
      // NOT before the .5s colour transition has landed, or the rasterizer
      // captures a half-faded value and the headline stays invisible on paper.
      clearTimeout(themeRedraw);
      themeRedraw = setTimeout(() => {
        pixelHosts.forEach((h) => { if (h && h.redraw) h.redraw(); });
        paintRimPalette();      // the rim answers to the accent AND to the ground
      }, 600);
    });
  }

  /* ============================================================
     3) NAV — condense on scroll
     The nav does NOT auto-hide. Pac-Man's line is a separate fixed
     canvas — sliding the bar away left him drawing over random page
     content with nothing behind him, which read as a broken element.
     ============================================================ */
  const nav = d.getElementById("nav");
  if (nav) {
    addEventListener("scroll", () => {
      /* 8, not 24: the owner asked for the transition to belong to the
         first movement. At 24 there was a stretch of scrolling where the
         bar had not decided yet. */
      nav.classList.toggle("stuck", scrollY > 8);
    }, { passive: true });
  }

  /* ============================================================
     4) MAGNETIC BUTTONS
     (no custom cursor ring — Pac-Man owns the pointer gags)
     ============================================================ */
  if (fine && !reduced) {
    d.querySelectorAll("[data-magnet]").forEach((el) => {
      el.addEventListener("pointermove", (e) => {
        const r = el.getBoundingClientRect();
        const mx = e.clientX - (r.left + r.width / 2);
        const my = e.clientY - (r.top + r.height / 2);
        el.style.transform = `translate(${mx * 0.22}px, ${my * 0.3}px)`;
      });
      el.addEventListener("pointerleave", () => { el.style.transform = ""; });
    });
  }

  /* ============================================================
     5) VELOCITY MARQUEE — scroll speed drives speed, skew, direction
     ============================================================ */
  const vmq = d.getElementById("vmq");
  if (vmq && !reduced) {
    vmq.innerHTML += vmq.innerHTML;          // seamless second copy
    let x = 0, vel = 0, raf = null, halfW = 0;

    // scrollWidth forces a synchronous layout. Reading it per frame — right
    // after writing a transform on the same element — was a guaranteed reflow
    // every frame. The track's width only changes on resize and once the
    // webfont swaps in, so measure it exactly there.
    //
    // And NOT eagerly here: reading it straight after doubling the markup made
    // the browser lay out the whole, now very wide, track in the middle of the
    // boot script — 125 ms of forced reflow. run() measures on its first frame
    // instead, by which point layout has happened anyway.
    const measureMq = () => { halfW = vmq.scrollWidth / 2; };
    addEventListener("resize", measureMq);
    if (d.fonts && d.fonts.ready) d.fonts.ready.then(measureMq);

    if (window.PixelFX && PixelFX.onVelocity) PixelFX.onVelocity((v) => { vel = v; });

    const run = () => {
      const speed = 0.55 + vel * 0.42;       // scrolling up pushes it backwards
      x -= speed;
      if (!halfW) measureMq();               // first frames before layout settles
      const h = halfW;
      if (h > 0) {
        if (x <= -h) x += h;
        if (x > 0) x -= h;
      }
      vmq.style.transform = `translate3d(${x}px,0,0) skewX(${(-vel * 0.28).toFixed(2)}deg)`;
      raf = requestAnimationFrame(run);
    };

    // Only animate while the strip is actually on screen. It used to hold a
    // rAF loop writing a transform for the entire life of the page — invisible
    // work that still costs main-thread time and battery on every scroll.
    new IntersectionObserver((entries) => {
      const on = entries[0].isIntersecting;
      if (on && !raf) raf = requestAnimationFrame(run);
      else if (!on && raf) { cancelAnimationFrame(raf); raf = null; }
    }, { rootMargin: "120px 0px" }).observe(vmq.parentElement);
  }

  /* ============================================================
     6) CHIP TOOLTIPS
     ONE fixed card on <body> — it escapes every section's overflow
     and never touches layout, so it cannot cost a millisecond of CLS.

     Delegated from the document, not bound per element: the scores on
     the home page are rendered by a later script, and binding directly
     would have made this file's load order load-bearing.
     ============================================================ */
  (() => {
    const TIPS = (window.MCD && window.MCD.TIPS) || {};
    const tip = d.createElement("div");
    tip.className = "tip";
    tip.id = "chipTip";
    tip.setAttribute("role", "tooltip");
    // hidden from the a11y tree while empty — an empty role="tooltip" fails
    // the aria-tooltip-name audit, which is a whole Accessibility point
    tip.setAttribute("aria-hidden", "true");
    d.body.appendChild(tip);
    let cur = null;

    function show(el) {
      const t = TIPS[el.dataset.tip];
      if (!t) return;
      cur = el;
      tip.innerHTML = "";
      const b = d.createElement("b");
      b.textContent = t[0];
      tip.appendChild(b);
      tip.appendChild(d.createTextNode(t[1]));
      el.setAttribute("aria-describedby", "chipTip");
      tip.removeAttribute("aria-hidden");
      tip.classList.add("show");
      const r = el.getBoundingClientRect();
      const x = Math.max(12, Math.min(innerWidth - tip.offsetWidth - 12,
        r.left + r.width / 2 - tip.offsetWidth / 2));
      const y = r.top - tip.offsetHeight - 10;
      tip.style.left = x + "px";
      tip.style.top = (y < 12 ? r.bottom + 10 : y) + "px";
    }
    function hide() {
      if (cur) cur.removeAttribute("aria-describedby");
      cur = null;
      tip.classList.remove("show");
      tip.setAttribute("aria-hidden", "true");
    }

    // every chip must be reachable by keyboard, whenever it appears
    const focusable = (el) => {
      if (!el.hasAttribute("tabindex") && !/^(A|BUTTON|INPUT)$/.test(el.tagName)) {
        el.setAttribute("tabindex", "0");
      }
    };
    // One pass, once every deferred script has run — the home page renders its
    // score chips in v3.js, which loads after this file. NOT a MutationObserver
    // on <body>: the typewriter rewrites innerHTML every ~9 ms, so the observer
    // fired a document-wide querySelectorAll for every character typed.
    const markAll = () => d.querySelectorAll("[data-tip]").forEach(focusable);
    if (d.readyState === "complete") markAll();
    else d.addEventListener("DOMContentLoaded", markAll);

    d.addEventListener("pointerover", (e) => {
      if (e.pointerType !== "mouse") return;
      const chip = e.target.closest("[data-tip]");
      if (chip && chip !== cur) show(chip);
    });
    d.addEventListener("pointerout", (e) => {
      const chip = e.target.closest("[data-tip]");
      if (chip && chip === cur && !chip.contains(e.relatedTarget)) hide();
    });
    d.addEventListener("focusin", (e) => {
      const chip = e.target.closest("[data-tip]");
      if (chip) show(chip); else if (cur) hide();
    });
    // a tap explains the chip instead of doing nothing at all
    d.addEventListener("click", (e) => {
      const chip = e.target.closest("[data-tip]");
      if (chip) { if (cur === chip) hide(); else show(chip); return; }
      if (cur) hide();
    });
    addEventListener("scroll", () => { if (cur) hide(); }, { passive: true });
    d.addEventListener("keydown", (e) => { if (e.key === "Escape") hide(); });
  })();

  /* ============================================================
     7) FAQ TAB WIDGET — one implementation, two content sources
     The home page feeds it from data.js; a service page authors its
     questions as real HTML and passes the answer nodes. Either way the
     roles, the roving tabindex and the streaming are identical.

     `role="tab"` REQUIRES a `role="tablist"` parent — without it axe
     fails aria-required-parent, and that single rule was the whole
     reason Accessibility once sat at 95.
     ============================================================ */
  function faq(list, panel, answers) {
    if (!list || !panel || !answers.length) return;
    const tabs = [...list.querySelectorAll(".faq-q")];
    if (!tabs.length) return;
    const stream = window.MCD.stream;
    let cancel = () => { };

    function show(i, focus) {
      cancel();
      tabs.forEach((b, n) => {
        const on = n === i;
        b.setAttribute("aria-selected", String(on));
        // roving tabindex: Tab reaches the group once, arrows move inside it
        b.tabIndex = on ? 0 : -1;
        if (on && focus) b.focus();
      });
      panel.setAttribute("aria-labelledby", tabs[i].id);
      panel.innerHTML = '<span class="label"></span><div class="a"></div>';
      panel.querySelector(".label").textContent = tabs[i].dataset.q || tabs[i].textContent;
      cancel = stream(panel.querySelector(".a"), answers[i]);
    }

    list.addEventListener("click", (e) => {
      const b = e.target.closest(".faq-q");
      if (b) show(tabs.indexOf(b));
    });

    list.addEventListener("keydown", (e) => {
      const at = tabs.indexOf(d.activeElement);
      if (at < 0) return;
      const map = { ArrowDown: 1, ArrowRight: 1, ArrowUp: -1, ArrowLeft: -1 };
      let next = null;
      if (map[e.key]) next = (at + map[e.key] + tabs.length) % tabs.length;
      else if (e.key === "Home") next = 0;
      else if (e.key === "End") next = tabs.length - 1;
      if (next === null) return;
      e.preventDefault();
      show(next, true);
    });

    show(0);
  }

  /* A page that authors its FAQ in HTML gets it wired here; the home page
     renders its tabs from data.js and calls faq() itself afterwards.

     The answers are indented markup, so the source has to be un-indented
     before it reaches a pre-wrap panel: a blank line stays a paragraph break,
     every other line wrap collapses to a single space. */
  const clean = (s) => s.trim()
    .split(/\n[ \t]*\n/)                                  // blank line = new paragraph
    .map((par) => par.replace(/[ \t]*\n[ \t]*/g, " ").trim())  // a wrap is just a space
    .join("\n\n");

  const authored = d.getElementById("faqList");
  const authoredSrc = d.getElementById("faqSrc");
  if (authored && authoredSrc && authored.querySelector(".faq-q")) {
    faq(authored, d.getElementById("faqPanel"),
      [...authoredSrc.children].map((n) => clean(n.innerHTML)));
  }

  /* ============================================================
     8) CONTACT FORM — prototype only, never silently "succeeds"
     The home page and contact.html carry the same form, so the
     honest-failure note lives here rather than in both.
     ============================================================ */
  const cForm = d.getElementById("contactForm");
  if (cForm) {
    cForm.addEventListener("submit", (e) => {
      e.preventDefault();
      const note = d.getElementById("cNote");
      if (!note) return;
      note.innerHTML =
        "This is the <b>design prototype</b> — nothing was sent. On the live site this posts to Web3Forms. " +
        'Mail us directly at <a href="mailto:info@mccain-digital.com" style="text-decoration:underline">info@mccain-digital.com</a>.';
    });
  }

  /* ============================================================
     9) PIXEL ENGINE — headlines, buttons, pictures
     ============================================================ */
  // card selector → the box the engine samples, and how coarse the grid is
  const IMG_TARGETS = [
    { card: ".case", box: ".case-img", o: { gap: 4, size: 4, radius: 70, force: 2.8 } },
    { card: ".pcard", box: ".px-img", o: { gap: 3.5, size: 3.5, radius: 60, force: 3.2 } },
    { card: ".shot", box: ".shot-img", o: { gap: 4, size: 4, radius: 70, force: 2.8 } },
    /* THE HERO. Not a second implementation of the black hole - the same one,
       on the same call, because it is the same thing: pixels that scatter
       when the hole passes and spring back behind it. Rebuilding it on the
       dither field could push the cloud around but never destroy anything,
       there being no particles there to destroy.

       The card is the STAGE and not the picture, so the pointer is still
       tracked when it is over the headline - the copy sits above the canvas
       and would otherwise swallow every move.

       AND A COARSER GRID THAN THE CARDS USE, because the particle count is
       an AREA: at the cards' 4px stride a full-bleed header is 57,600
       particles against a card's 13,900, and the entrance cost 14 long tasks
       and a 117ms frame. 10px puts the count back where the cards are, and
       on a background that is not a loss - it is a coarser mosaic, which is
       what a ground should be next to type. */
    { card: ".stage", box: ".stage-shot .shot-img", o: { gap: 10, size: 10, radius: 70, force: 2.8 } }
  ];

  function bootPixels() {
    if (!window.PixelFX) return;
    pixelHosts = [...d.querySelectorAll("[data-pixel]")].map(PixelFX.headline);

    // headline() only prepares the field — the page decides WHEN it assembles.
    // One shot each, the moment it scrolls into view.
    const io = new IntersectionObserver((entries) => {
      entries.forEach((e) => {
        if (!e.isIntersecting) return;
        const inst = pixelHosts.find((h) => h.host === e.target);
        if (inst) inst.play();
        io.unobserve(e.target);
      });
    }, { threshold: 0.5, rootMargin: "0px 0px -6% 0px" });
    pixelHosts.forEach((h) => io.observe(h.host));

    let rt = null;
    addEventListener("resize", () => {
      clearTimeout(rt);
      rt = setTimeout(() => pixelHosts.forEach((h) => h.redraw()), 160);
    });

    // Buttons disintegrate on hover and vacuum the pixels back in on click.
    // EVERY yellow button gets it — the primary CTAs, the console's send key
    // and the "Open →" pill on each case — so the effect reads as the rule,
    // not as a decoration on two of them. Ghost buttons keep the magnetic pull
    // instead; two effects on one element fight each other.
    if (PixelFX.button) {
      d.querySelectorAll(".btn:not(.btn--ghost), .console-send, .case-peek")
        .forEach((b) => PixelFX.button(b));
    }

    // Pictures assemble out of a pixel swarm when they scroll in, then hand
    // themselves back sharp — and re-pixelate under the pointer. The reveal is
    // NOT gated on hover support: a phone gets the assembly, it just never
    // gets the black hole.
    if (PixelFX.image && !reduced) {
      const imgFx = new Map();

      const revealIO = new IntersectionObserver((entries) => {
        entries.forEach((e) => {
          if (!e.isIntersecting) return;
          const fx = imgFx.get(e.target);
          if (fx) fx.reveal();
          revealIO.unobserve(e.target);
        });
      }, { threshold: 0.3 });

      // the engine wants the CONTAINER (it finds the <img> itself and appends
      // its canvas there); it returns null when there is nothing to sample
      const wire = (card, box, opts) => {
        const fx = box && PixelFX.image(box, opts);
        if (!fx) return;
        imgFx.set(box, fx);
        revealIO.observe(box);
        if (PixelFX.noHover) return;
        card.addEventListener("pointerenter", () => fx.enter("hover"));
        card.addEventListener("pointerleave", () => fx.leave("hover"));
        card.addEventListener("focusin", () => fx.enter("focus"));
        card.addEventListener("focusout", () => fx.leave("focus"));
      };

      IMG_TARGETS.forEach((t) => {
        d.querySelectorAll(t.card).forEach((card) => {
          wire(card, card.querySelector(t.box), Object.assign({ track: card }, t.o));
        });
      });
    }
  }


  /* ============================================================
     8) THE REFRESH — word reveals and the header field

     Both are OPT-IN from the markup, on purpose: the pages that still
     rasterise their headlines with the pixel engine must not have the
     same text split into word spans underneath the raster. A page joins
     the refresh by saying so.

       data-words   on a heading  -> its words rise through a mask
       data-field   on a header   -> the dither field runs behind it
     ============================================================ */

  /* Walks TEXT NODES only, so the markup around them survives: the <br>
     in a hero headline, the .dim span that greys half a section heading,
     the .accent span that carries the yellow. Rewriting the heading as a
     string would have destroyed all three. */
  function splitWords(root) {
    const walk = d.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    let n, i = 0;
    while ((n = walk.nextNode())) nodes.push(n);
    nodes.forEach((tn) => {
      if (!tn.nodeValue.trim()) return;
      const frag = d.createDocumentFragment();
      tn.nodeValue.split(/(\s+)/).forEach((part) => {
        if (!part) return;
        if (!part.trim()) { frag.appendChild(d.createTextNode(part)); return; }
        const w = d.createElement("span");
        w.className = "w";
        const inner = d.createElement("i");
        inner.textContent = part;
        inner.style.setProperty("--wi", i++);
        w.appendChild(inner);
        frag.appendChild(w);
      });
      tn.parentNode.replaceChild(frag, tn);
    });
    return i;
  }

  if (!reduced) {
    d.querySelectorAll("[data-words]").forEach((h) => {
      splitWords(h);
      h.classList.add("wr");
    });

    /* The header is a SEQUENCE, not a reveal: a view() timeline cannot
       animate what is already on screen at load, because its entry range
       is behind us before the first frame. The hidden state is added
       here rather than in the stylesheet, so a visitor whose JavaScript
       never arrives gets the finished headline instead of an empty
       header. */
    const stage = d.querySelector(".hero--stage");
    if (stage) {
      const h1 = stage.querySelector(".hero-h");
      if (h1) {
        h1.classList.remove("wr");
        splitWords(h1);
        h1.classList.add("hs");
      }
      stage.classList.add("hs");
      requestAnimationFrame(() => requestAnimationFrame(() => {
        if (h1) h1.classList.add("go");
        stage.classList.add("go");
      }));
    }
  }

  /* The dither field, behind the header and nowhere else - the owner
     asked for it there only. The engine caps its own ramp against the
     dimmest text on the host, so asking for a brighter top cannot make
     the header fail contrast; it simply gets clamped. */
  function bootField() {
    if (reduced || !window.PixelFX || !PixelFX.dither) return;
    d.querySelectorAll("[data-field]").forEach((el) => {
      PixelFX.dither(el, { cell: 9, top: .5 });
    });
  }
  if (d.readyState === "complete") bootField();
  else addEventListener("load", bootField);

  // The page scripts run between this file and the boot: they clone the work
  // track and render the service cards synchronously, so by the time the font
  // promise resolves the DOM the engine walks is already complete.
  if (d.fonts && d.fonts.ready) {
    Promise.all([embedFont(), d.fonts.ready]).then(bootPixels);
  } else {
    embedFont().then(bootPixels);
  }

  /* ============================================================
     THE TAB LOSES FOCUS — the mark scatters, the title says goodbye

     From the original site, which had it before this rebuild did. Two
     departures from its version:

     - it re-typed the two glyphs onto a canvas to scatter them; this loads
       the REAL favicon and throws ITS pixels, so changing the logo changes
       its dissolve with it. A second drawing of a logo is a second logo.
     - it built the image on the first blur. An SVG has to load first, so
       this builds it once the page is idle and has it waiting.

     Everything else is the original's: the ink tile stays, only the letters
     come apart, and they scatter inside a 14px box on a 2px grid.
     ============================================================ */
  function bootFavicon() {
    const link = d.querySelector('link[rel="icon"]');
    if (!link || !link.href) return;

    const home = link.href;
    const homeTitle = d.title;
    let away = null;

    const build = () => new Promise((done) => {
      const img = new Image();
      img.onload = () => {
        try {
          const c = d.createElement("canvas");
          c.width = c.height = 64;
          const x = c.getContext("2d");
          if (!x || !x.roundRect) return done(null);
          x.drawImage(img, 0, 0, 64, 64);
          const src = x.getImageData(0, 0, 64, 64).data;

          // the tile is repainted flat, then the letters are thrown back on
          x.clearRect(0, 0, 64, 64);
          x.fillStyle = "#0f0e0c";
          x.beginPath();
          x.roundRect(0, 0, 64, 64, 15);
          x.fill();

          for (let py = 0; py < 64; py += 2) {
            for (let px = 0; px < 64; px += 2) {
              const i = (py * 64 + px) * 4;
              const r = src[i], g = src[i + 1], b = src[i + 2];
              // the ink tile stays put; only what is brighter than it moves
              if (src[i + 3] > 40 && (r > 60 || g > 60)) {
                x.fillStyle = "rgb(" + r + "," + g + "," + b + ")";
                x.fillRect(px + (Math.random() - .5) * 14,
                           py + (Math.random() - .5) * 14, 2, 2);
              }
            }
          }
          done(c.toDataURL("image/png"));
        } catch (e) {
          done(null);            // a tainted or unsupported canvas: no effect
        }
      };
      img.onerror = () => done(null);
      img.src = home;
    });

    const idle = window.requestIdleCallback || ((f) => setTimeout(f, 800));
    idle(() => { build().then((url) => { away = url; }); });

    d.addEventListener("visibilitychange", () => {
      if (d.hidden) {
        if (away) link.href = away;
        d.title = "we\u2019ll be here. \u2014 mccain digital";
      } else {
        link.href = home;
        d.title = homeTitle;
      }
    });
  }
  bootFavicon();

  window.MCDUI = { faq, reduced, fine, ROOT };
})();
