/* GENERATED by tools/v5build.mjs from the page logic in index.html - do not edit. */
class V5Logic {
  static GOALIAS = { process: ['ablauf'], studio: ['menschen'], work: ['faelle', 'produkte'], services: ['faehigkeiten', 'leistung', 'handwerk', 'kette'], ai: ['ai'], faq: ['faq'] };
  static GOTO = { services: '/leistungen/', pricing: '/preise/', recall: '/md-recall/', process: '/leistungen/web-apps/#ablauf', stack: '/leistungen/web-apps/#stack', work: '/studio/#produkte', studio: '/studio/#menschen', contact: '/kontakt/#contact', services: '/leistungen/ki-automatisierung/', faq: '/leistungen/ki-automatisierung/#faq', ai: '/leistungen/ki-automatisierung/#ai' };
  static DEMO = [
    { q: { de: 'Was kostet eine Website?', en: 'What does a website cost?' }, a: { de: 'Es gibt keine Preisliste – Sie erhalten innerhalb von 48 Stunden ein Festpreisangebot. Eine kleine Website beginnt im niedrigen fünfstelligen Bereich.', en: 'There is no price list — you receive a fixed quote within 48 hours. A small website starts in the low five figures.' } },
    { q: { de: 'Wer baut das konkret?', en: 'Who actually builds it?' }, a: { de: 'Die zwei Gründer: Christian entwickelt, Kathi verantwortet Design und Marke. Keine Junioren, keine Übergaben.', en: 'The two founders: Christian builds, Kathi does design and brand. No juniors, no hand-offs.' } },
    { q: { de: 'Wie lange dauert eine Web-App?', en: 'How long does a web app take?' }, a: { de: 'Ein MVP typischerweise 6–12 Wochen. Etwas Klickbares sehen Sie in der ersten Woche.', en: 'An MVP typically takes 6–12 weeks. You see something clickable in the first week.' } }
  ];
  static COVER = 'article, button, a, input, textarea, select, label, header, [role="dialog"], [data-screen-label="Modal"], .pxbtn, [data-cover]';
  static GRAD = ['#FFB46B', '#FF5A8C', '#C05CFF', '#5FC3FF', '#FF8FB8'];

  reduced() { return this.props.motion === false || (typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches); }

  accent() { const a = this.props.accent; return (typeof a === 'string' && /^#[0-9a-f]{6}$/i.test(a)) ? a : '#635BFF'; }

  hexRgb(h) { return [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)]; }

  initFx() {
    if (typeof IntersectionObserver !== 'function') return;
    this.fxIo = new IntersectionObserver((es) => es.forEach((e) => {
      if (!e.isIntersecting) { e.target.setAttribute('data-off', ''); if (e.target._loop) { clearInterval(e.target._loop); e.target._loop = 0; } return; }
      e.target.removeAttribute('data-off');
      const nums = e.target.querySelectorAll('[data-fxnum]');
      if (!nums.length || e.target._loop) return;
      const run = () => nums.forEach((n) => this.countTo(n));
      run(); e.target._loop = setInterval(run, 7000);
    }), { rootMargin: '0px 0px -8% 0px' });
    const scan = () => { document.querySelectorAll('[data-fx]').forEach((el) => { if (el._fx) return; el._fx = 1; el.setAttribute('data-off', ''); this.watchShown(this.fxIo, el); }); };
    scan(); setTimeout(scan, 900); setTimeout(scan, 2500);
  }

  countTo(el) {
    const to = parseFloat(el.getAttribute('data-fxnum')) || 0, t0 = performance.now(), dur = 1250, tok = (el._tok = (el._tok || 0) + 1);
    const step = (t) => { if (el._tok !== tok) return; const p = Math.min(1, (t - t0) / dur), e = 1 - Math.pow(1 - p, 3); el.textContent = Math.round(to * e); if (p < 1) requestAnimationFrame(step); };
    requestAnimationFrame(step);
  }

  dgRef = (el) => {
    if (!el || this.dgEl === el) return; this.dgEl = el;
    if (typeof IntersectionObserver !== 'function') return;
    if (this.dgIo) this.dgIo.disconnect(); if (this.dgRo) this.dgRo.disconnect();
    this.dgIo = new IntersectionObserver((es) => { const vis = es[0] && es[0].isIntersecting; const lay = el.querySelector('[data-dgflow]'); const setP = (p) => { if (!lay || !lay.getAnimations) return; lay.getAnimations({ subtree: true }).forEach((an) => { try { p ? an.pause() : an.play(); } catch (e) {} }); };
      this.dgVisible = vis;
      if (vis) { if (this.dgStale) redo(); this.dgAutoStart(); this.dgPulseStart(); setP(false); } else { this.dgAutoStop(); this.dgPulseStop(); setP(true); } }, { rootMargin: '-10% 0px' });
    this.watchShown(this.dgIo, el);
    const redo = () => { if (this.isSkipped(el)) { this.dgStale = true; return; } this.dgStale = false; cancelAnimationFrame(this.dgRaf); this.dgRaf = requestAnimationFrame(() => this.dgPaths()); }; this.dgRedo = redo;
    setTimeout(redo, 120); setTimeout(redo, 900);
    if (typeof ResizeObserver === 'function') { if (this.dgRo) this.dgRo.disconnect(); this.dgRo = new ResizeObserver(redo); this.dgRo.observe(el); }
  };

  dgPaths() {
    const root = this.dgEl; if (!root) return;
    const layer = root.querySelector('[data-dgflow]'); if (!layer) return;
    const host = layer.parentElement, hb = host.getBoundingClientRect();
    const nodes = Array.from(root.querySelectorAll('[data-dgnode]')).map((el) => { const r = el.getBoundingClientRect(); return { id: el.getAttribute('data-dgnode'), x: r.left - hb.left, y: r.top - hb.top, w: r.width, h: r.height, cx: r.left - hb.left + r.width / 2, cy: r.top - hb.top + r.height / 2 }; });
    if (nodes.length < 4 || !hb.width) return;
    const rows = {}; nodes.forEach((n) => { const k = Math.round(n.cy / 12); (rows[k] = rows[k] || []).push(n); });
    const order = Object.keys(rows).sort((a, b) => a - b).map((k) => rows[k]);
    if (order.length < 2) return;
    layer.textContent = '';
    const C = ['#FFB46B', '#FF5A8C', '#C05CFF', '#5FC3FF', '#9F99FF'], out = hb.width - 4;
    const legs = [];
    for (let i = 0; i < order.length - 1; i++) {
      const from = order[i], to = order[i + 1], gapY = (from[0].y + from[0].h + to[0].y) / 2;
      from.forEach((a, k) => { const b = to[Math.min(to.length - 1, k % to.length)]; legs.push({ c: C[(i + k) % C.length], pts: [[a.cx, a.cy], [a.cx, gapY], [b.cx, gapY], [b.cx, b.cy]] }); });
    }
    Array.from(root.querySelectorAll('[data-dgfeed]')).forEach((el, k) => {
      const r = el.getBoundingClientRect(), row = el.closest('div[style*="grid-template-columns"]');
      const main = row && row.querySelector('[data-dgnode]'); if (!main) return;
      const m = main.getBoundingClientRect();
      const sx = r.left - hb.left + r.width / 2, sy = r.top - hb.top, ty = m.top - hb.top + m.height / 2, tx = m.left - hb.left + m.width - 6;
      legs.push({ c: C[(k + 2) % C.length], feed: true, pts: [[sx, sy], [sx, sy - 9], [tx, sy - 9], [tx, ty]] });
    });
    order[order.length - 1].forEach((a, k) => legs.push({ c: C[k % C.length], pts: [[a.cx, a.cy], [a.cx, a.y + a.h + 10], [out, a.y + a.h + 10]] }));
    const pool = legs.concat(legs).sort(() => Math.random() - 0.5).slice(0, 30); pool.forEach((leg, i) => {
      const el = document.createElement('span');
      const sz = 3 + Math.round(Math.random() * 2); el.style.cssText = 'position:absolute;left:0;top:0;width:' + sz + 'px;height:' + sz + 'px;margin:' + (-sz / 2) + 'px 0 0 ' + (-sz / 2) + 'px;background:' + leg.c + ';opacity:' + (0.6 + Math.random() * 0.4).toFixed(2) + ';will-change:transform';
      layer.appendChild(el);
      const total = leg.pts.reduce((s, p, j) => j ? s + Math.abs(p[0] - leg.pts[j - 1][0]) + Math.abs(p[1] - leg.pts[j - 1][1]) : 0, 0) || 1;
      let acc = 0;
      const frames = leg.pts.map((p, j) => { if (j) acc += Math.abs(p[0] - leg.pts[j - 1][0]) + Math.abs(p[1] - leg.pts[j - 1][1]); return { transform: 'translate(' + p[0] + 'px,' + p[1] + 'px)', offset: Math.min(1, acc / total), opacity: j === 0 ? 0 : (j === leg.pts.length - 1 ? 0 : 1) }; });
      frames[0].opacity = 0; if (frames[1]) frames[1].opacity = 1;
      const anim = el.animate(frames, { duration: (leg.feed ? 1500 : 2000) + Math.random() * (leg.feed ? 1200 : 2600), iterations: Infinity, delay: Math.random() * 3200, easing: 'linear' });
      if (this.dgVisible === false) anim.pause();
    });
  }

  dgPulse() {
    const root = this.dgEl; if (!root) return;
    const layer = root.querySelector('[data-dgflow]'); if (!layer) return;
    const host = layer.parentElement, hb = host.getBoundingClientRect(); if (!hb.width) return;
    const rowsEls = Array.from(host.children).filter((c) => c.hasAttribute && !c.hasAttribute('data-dgflow'));
    const byRow = rowsEls.map((rEl) => Array.from(rEl.querySelectorAll('[data-dgnode]')));
    if (byRow.length < 2) return;
    const pt = (el) => { const r = el.getBoundingClientRect(); return { x: r.left - hb.left + r.width / 2, y: r.top - hb.top + r.height / 2, el: el }; };
    const chain = byRow.filter((n) => n.length).map((n) => pt(n[Math.floor(Math.random() * n.length)]));
    if (chain.length < 2) return;
    const pts = [];
    const star = chain[Math.min(chain.length - 1, 1 + Math.floor(Math.random() * 3))];
    if (star && star.el && (!this.dgUserAt || Date.now() - this.dgUserAt > 9000)) { const id = star.el.getAttribute('data-dgnode'); setTimeout(() => { if (this.mounted && this.state.dgPick !== id) this.setState({ dgPick: id, dgHover: null }); }, 900); }
    chain.forEach((p, i) => { if (i) { const prev = chain[i - 1], midY = (prev.y + p.y) / 2; pts.push([prev.x, midY], [p.x, midY]); } pts.push([p.x, p.y]); });
    pts.push([hb.width - 2, chain[chain.length - 1].y]);
    const total = pts.reduce((s, p, j) => j ? s + Math.abs(p[0] - pts[j - 1][0]) + Math.abs(p[1] - pts[j - 1][1]) : 0, 0) || 1;
    let acc = 0;
    const frames = pts.map((p, j) => { if (j) acc += Math.abs(p[0] - pts[j - 1][0]) + Math.abs(p[1] - pts[j - 1][1]); return { transform: 'translate(' + p[0] + 'px,' + p[1] + 'px)', offset: Math.min(1, acc / total) }; });
    const DUR = 3000;
    for (let k = 0; k < 7; k++) {
      const el = document.createElement('span'), sz = k === 0 ? 9 : 7 - Math.min(4, k);
      el.style.cssText = 'position:absolute;left:0;top:0;width:' + sz + 'px;height:' + sz + 'px;margin:' + (-sz / 2) + 'px 0 0 ' + (-sz / 2) + 'px;background:' + (k ? '#9F99FF' : '#fff') + ';opacity:' + (k ? (0.7 - k * 0.09).toFixed(2) : 1) + ';box-shadow:0 0 ' + (k ? 8 : 16) + 'px ' + (k ? 2 : 5) + 'px rgba(159,153,255,' + (k ? .35 : .75) + ')';
      layer.appendChild(el);
      const an = el.animate(frames, { duration: DUR, delay: k * 55, easing: 'linear', fill: 'both' });
      an.onfinish = () => el.remove();
    }
    chain.forEach((p, i) => {
      const at = (i / (chain.length - 0.0001)) * DUR;
      setTimeout(() => {
        const el = p.el, row = el.closest('div[style*="grid-template-columns"]');
        const prevBg = el.style.boxShadow;
        el.style.transition = 'box-shadow .18s, transform .18s'; el.style.boxShadow = 'inset 0 0 0 1px #fff, 0 0 26px 4px rgba(159,153,255,.6)'; el.style.transform = 'translateY(-2px)';
        if (row) { row.style.transition = 'background .25s'; row.style.background = 'rgba(99,91,255,.10)'; }
        setTimeout(() => { el.style.boxShadow = prevBg; el.style.transform = 'none'; if (row) row.style.background = 'transparent'; }, 620);
      }, at);
    });
    const card = root.querySelector('[data-dgout]');
    if (card) setTimeout(() => { card.style.transition = 'box-shadow .25s'; card.style.boxShadow = '0 0 0 1px rgba(159,153,255,.8), 0 0 40px 4px rgba(99,91,255,.35)'; setTimeout(() => { card.style.boxShadow = 'none'; }, 900); }, DUR - 120);
  }

  dgPulseStart() { if (this.dgPulseT) return; const go = () => { if (this.mounted) this.dgPulse(); }; setTimeout(go, 400); this.dgPulseT = setInterval(go, 5200); }

  dgPulseStop() { if (this.dgPulseT) { clearInterval(this.dgPulseT); this.dgPulseT = 0; } }

  dgAutoStart() {}

  dgAutoStop() {}

  dgTouch = () => { this.dgUserAt = Date.now(); };

  keyActivate = (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); e.currentTarget.click(); } };

  go(id) {
    this.setState({ menu: null, mobileOpen: false });
    if (this.state.modal) this.closeModal();
    const root = this.rootEl || document;
    let el = root.querySelector('#' + id);
    if (!el) { const alts = V5Logic.GOALIAS[id] || []; for (let i = 0; i < alts.length && !el; i++) el = root.querySelector('#' + alts[i]); }
    if (!el) { const to = V5Logic.GOTO[id]; if (to) window.location.href = to; return; }
    const top = id === 'top' ? 0 : el.getBoundingClientRect().top + window.scrollY - 72;
    window.scrollTo({ top, behavior: this.reduced() ? 'auto' : 'smooth' });
  }

  goHandler(id) { this._go = this._go || {}; if (!this._go[id]) this._go[id] = (e) => { if (e && e.preventDefault) e.preventDefault(); this.go(id); }; return this._go[id]; }

  onPointer = (e) => { if (e.pointerType === 'touch') return; this.mouse = { x: e.clientX, y: e.clientY, t: performance.now() }; };

  onKey = (e) => { if (e.key === 'Escape') { if (this.state.modal) this.closeModal(); else if (this.state.mobileOpen) this.setState({ mobileOpen: false }); else if (this.state.menu) this.setState({ menu: null }); } };

  onScroll = () => { if (this.scrollRaf) return; this.scrollRaf = requestAnimationFrame(() => { this.scrollRaf = 0; if (!this.mounted) return; const sc = window.scrollY > 12; if (sc !== this.state.scrolled) this.setState({ scrolled: sc }); this.updateProcess(); const bar = this.rootEl && this.rootEl.querySelector('[data-progress]'); if (bar) { const d = document.documentElement; const max = Math.max(1, d.scrollHeight - window.innerHeight); bar.style.transform = 'scaleX(' + Math.min(1, window.scrollY / max).toFixed(4) + ')'; } }); };

  watchConsole(root) {
    if (this.consoleWatched || typeof IntersectionObserver !== 'function') return; this.consoleWatched = true;
    // only a full console (with its own transcript) may hide the dock – a plain ask block must not
    const el = root.querySelector('[data-console-full]');
    if (!el) { if (this.state.aiVisible) this.setState({ aiVisible: false }); }
    else { this.consoleIo = new IntersectionObserver((es) => { const vis = es[0].isIntersecting; if (vis !== this.state.aiVisible) this.setState({ aiVisible: vis }); }, { rootMargin: '120px 0px' }); this.watchShown(this.consoleIo, el, () => { if (this.state.aiVisible) this.setState({ aiVisible: false }); }); }
    // the dock only appears once the hero (with its own input) has scrolled away
    const hero = root.querySelector('[data-screen-label="Hero A"]'); if (hero) { this.heroIo = new IntersectionObserver((es) => { const vis = es[0].isIntersecting; if (vis !== this.state.heroVisible) this.setState({ heroVisible: vis }); }, { rootMargin: '-64px 0px 0px 0px' }); this.heroIo.observe(hero); }
  }

  startDemo() {
    clearTimeout(this.demoT); this.demoIdx = this.demoIdx || 0;
    const run = () => {
      const root = this.rootEl; if (!root || !this.mounted) return;
      const qEl = root.querySelector('[data-demo-q]'), aEl = root.querySelector('[data-demo-a]');
      if (!qEl || !aEl) { this.demoT = setTimeout(run, 800); return; }
      const pairs = this.loc(V5Logic.DEMO), pair = pairs[this.demoIdx % pairs.length];
      qEl.textContent = pair.q; aEl.textContent = '';
      if (this.reduced()) { aEl.textContent = pair.a; this.demoIdx++; this.demoT = setTimeout(run, 6000); return; }
      let k = 0;
      const tick = () => { if (!this.mounted) return; k += 2; aEl.textContent = pair.a.slice(0, k); if (k < pair.a.length) this.demoT = setTimeout(tick, 16); else { this.demoIdx++; this.demoT = setTimeout(run, 4200); } };
      this.demoT = setTimeout(tick, 700);
    };
    run();
  }

  initFlow(root) {
    const fl = root.querySelectorAll('[data-flow]:not([data-fl])'); if (!fl.length) return;
    if (!this.flowIo) this.flowIo = new IntersectionObserver((en) => en.forEach((e) => { e.target.querySelectorAll('[data-anim]').forEach((a) => { a.style.animationPlayState = e.isIntersecting ? 'running' : 'paused'; }); }), { rootMargin: '160px 0px' });
    fl.forEach((el) => { el.setAttribute('data-fl', '1'); this.watchShown(this.flowIo, el); });
  }

  initPixels(root) {
    const PX = window.PixelFX; if (!PX || this.reduced()) return;
    root.querySelectorAll('[data-px]:not([data-pxd])').forEach((b) => { b.setAttribute('data-pxd', '1'); try { PX.button(b); } catch (e) {} });
    root.querySelectorAll('[data-px-img]:not([data-pxd])').forEach((box) => {
      box.setAttribute('data-pxd', '1'); const img = box.querySelector('img'); if (!img) return;
      const wire = () => { try { const fx = PX.image(box, { gap: 4, size: 4, radius: 70, force: 2.8, track: box }); if (!fx) return; box.addEventListener('pointerenter', () => fx.enter('hover')); box.addEventListener('pointerleave', () => fx.leave('hover')); } catch (e) {} };
      if (img.complete && img.naturalWidth) wire(); else img.addEventListener('load', wire, { once: true });
    });
  }

  initReveal() {
    const root = this.rootEl; if (!root) return;
    this.initFlow(root); this.initPixels(root); this.watchConsole(root);
    const els = root.querySelectorAll('[data-reveal]:not([data-rv])'); if (!els.length) return;
    if (!this.io) this.io = new IntersectionObserver((entries) => { entries.forEach((e) => { if (e.isIntersecting) { const el = e.target; el.style.opacity = '1'; el.style.transform = 'none'; this.unwatch(this.io, el); if (el.hasAttribute('data-count-group')) this.runCounters(el); } }); }, { threshold: 0.08, rootMargin: '0px 0px -10% 0px' });
    const reduced = this.reduced();
    els.forEach((el) => { el.setAttribute('data-rv', '1'); if (reduced) return; const d = parseFloat(el.getAttribute('data-reveal')) || 0; const isHead = !!el.querySelector(':scope > h2, :scope > h3, :scope > div > h2'); const isTile = !!el.querySelector(':scope > article'); const dist = isTile ? 34 : isHead ? 18 : 26; const dur = isTile ? 0.9 : 0.7; el.style.opacity = '0'; el.style.transform = 'translateY(' + dist + 'px)'; el.style.transition = 'opacity ' + (dur * 0.8).toFixed(2) + 's cubic-bezier(.2,.8,.2,1) ' + d + 's, transform ' + dur + 's cubic-bezier(.16,1,.3,1) ' + d + 's'; this.watchShown(this.io, el); });
  }

  runCounters(group) {
    group.querySelectorAll('[data-count]').forEach((el) => {
      const to = parseFloat(el.getAttribute('data-count')), from = parseFloat(el.getAttribute('data-from') || '0'), pre = el.getAttribute('data-prefix') || '', suf = el.getAttribute('data-suffix') || '';
      const t0 = performance.now(), dur = 1400;
      const step = (now) => { const p = Math.min(1, (now - t0) / dur), e = 1 - Math.pow(1 - p, 3); el.textContent = pre + Math.round(from + (to - from) * e) + suf; if (p < 1) requestAnimationFrame(step); };
      requestAnimationFrame(step);
    });
  }

  updateProcess() {
    const root = this.rootEl, wrap = root && root.querySelector('[data-process-steps]'); if (!wrap) return;
    const r = wrap.getBoundingClientRect(), mid = window.innerHeight * 0.55;
    const p = Math.max(0, Math.min(1, (mid - r.top) / Math.max(1, r.height - 40)));
    const fill = wrap.querySelector('[data-process-fill]'); if (fill) fill.style.height = (p * 100).toFixed(1) + '%';
    let cur = 0;
    wrap.querySelectorAll('[data-step]').forEach((s, i) => { const on = s.getBoundingClientRect().top < mid; if (on) cur = i; const dot = s.querySelector('[data-step-dot]'); if (dot) { dot.style.background = on ? 'var(--acc)' : '#fff'; dot.style.borderColor = on ? 'var(--acc)' : 'rgba(10,37,64,.12)'; dot.style.color = on ? '#fff' : '#0A2540'; } });
    const ind = root.querySelector('[data-process-current]'); if (ind) ind.textContent = '0' + (cur + 1);
  }

  movePointsGlobal(tm, canvas) {
    const root = this.rootEl; if (!root) return;
    if (this.ptGate === undefined) {
      this.ptGate = window.matchMedia ? window.matchMedia('(min-width:1280px) and (pointer:fine)') : null;
      const arm = () => setTimeout(() => { this.ptLate = 1; }, 10000);
      if (document.readyState === 'complete') arm();
      else window.addEventListener('load', arm, { once: true });
    }
    if (!this.ptLate || (this.ptGate && !this.ptGate.matches)) return;
    if (!canvas._ptRO && window.ResizeObserver) {
      canvas._ptRO = new ResizeObserver(() => { canvas._ptDirty = 1; });
      canvas._ptRO.observe(root);
    }
    if (!canvas._pool || canvas._ptDirty || this.ptStale || (tm - (canvas._ptT || 0)) > 30) {
      this.ptStale = false;
      const layer = root.querySelector('[data-pt-layer]'); if (!layer) return;
      const sy0 = this.view.sy, avoid = [];
      root.querySelectorAll('[data-avoid], [data-hero-copy], h1, h2, h3, h4, p, li, button, a, img, svg, form, footer').forEach((a) => { if (a.closest('header, [data-pt-layer], [role="dialog"]') || this.isSkipped(a)) return; const c = a.getBoundingClientRect(); if (c.width < 24 || c.height < 10) return; avoid.push({ left: c.left - 12, right: c.right + 12, top: c.top + sy0 - 22, bottom: c.bottom + sy0 + 10 }); });
      const prev = canvas._pool ? canvas._pool.els : [];
      const els = Array.from(layer.querySelectorAll('[data-pt]')).map((el, i) => { const o = prev[i] && prev[i].el === el ? prev[i] : { off: 0, on: false, x: 0, y: 0 }; return { el, i, off: o.off, on: o.on, x: o.x, y: o.y, w: el.offsetWidth || 120, h: el.offsetHeight || 26 }; });
      canvas._pool = { els, avoid, span: Math.max(window.innerHeight * 2, document.documentElement.scrollHeight) + 240 }; canvas._ptT = tm; canvas._ptDirty = 0;
      if (this.ptHot) this.ptHot = els.find((n) => n.el === this.ptHot.el) || null;
    }
    const P = canvas._pool, els = P.els, N = els.length; if (!N) return;
    const dt = canvas._lastTm == null ? 0 : tm - canvas._lastTm; canvas._lastTm = tm;
    const W = this.view.w, VH = this.view.h, sy = this.view.sy, t = tm * 0.10, D = [-0.62, 0.5, -0.3, 0.68, 0.05, -0.7, 0.32, -0.45, 0.6, -0.15, 0.2, -0.55, 0.42, -0.05], m = this.mouse || { x: -9999, y: -9999 };
    let hit = null;
    for (let i = 0; i < N; i++) {
      const n = els[i], el = n.el;
      if (n === this.ptHot && n.on && m.x >= n.x && m.x <= n.x + n.w && m.y >= n.y && m.y <= n.y + n.h) { n.off += dt; hit = n; continue; }
      const speed = 34 + 30 * (((i * 7) % 6) / 5), yDoc = ((i / N) * P.span + (tm - n.off) * speed) % P.span - 120, yV = yDoc - sy;
      if (yV < -60 || yV > VH + 20) { if (n.on) { n.on = false; el.style.opacity = '0'; el.style.visibility = 'hidden'; } continue; }
      const th = yDoc / 2400 * 6.2832 + 0.18, cx = W * (0.5 + 0.56 * Math.sin(th)) + 0.04 * W * Math.sin(t * 0.6 + yDoc / 500), hw = W * (0.12 + 0.03 * Math.sin(th * 2.0));
      const x = cx + D[i % D.length] * hw, cw = n.w;
      let fade = Math.min(1, (W - 12 - x - cw) / 60, (x - 10) / 60);
      for (let k = 0; k < P.avoid.length; k++) { const a = P.avoid[k]; if (yDoc > a.top && yDoc < a.bottom && x + cw > a.left && x < a.right) { fade = 0; break; } }
      if (!n.on) { n.on = true; el.style.visibility = 'visible'; }
      n.x = x; n.y = yV;
      if (fade > 0.5 && m.x >= x && m.x <= x + cw && m.y >= yV && m.y <= yV + n.h) hit = n;
      el.style.transform = 'translate3d(' + Math.round(x) + 'px,' + Math.round(yV) + 'px,0)'; el.style.opacity = Math.max(0, fade).toFixed(2);
    }
    if (this.state.modal) hit = null;
    if (hit && hit !== this.ptHot) { const top = document.elementFromPoint(m.x, m.y); if (top && top.closest(V5Logic.COVER)) hit = null; }
    if (hit !== this.ptHot) { this.ptHot = hit; document.body.style.cursor = hit ? 'pointer' : ''; const p = hit && this._pts ? this._pts[hit.i] : null; this.setHover(p ? p.to : null); }
  }

  movePoints(tm, canvas, cfg, w, isHero) {
    const host = canvas.parentElement; if (!host) return;
    if (!canvas._pts || !canvas._pts.length || (tm - (canvas._ptT || 0)) > 2) { canvas._pts = Array.from(host.querySelectorAll('[data-pt]')); canvas._ptT = tm; const rr = canvas.getBoundingClientRect(); canvas._avoid = Array.from(host.querySelectorAll('[data-hero-copy], [data-avoid]')).map((a) => { const c = a.getBoundingClientRect(); return { left: c.left - rr.left - 12, right: c.right - rr.left + 12, top: c.top - rr.top - 24, bottom: c.bottom - rr.top + 8 }; }); }
    const els = canvas._pts; if (!els.length) return;
    const r = canvas.getBoundingClientRect(), W = r.width, H = r.height; if (W < 10 || H < 10) return;
    const asp = W / H, t = tm * 0.10, N = els.length, D = [-0.62, 0.5, -0.3, 0.68, 0.05, -0.7, 0.32, -0.45, 0.6, -0.15, 0.2, -0.55, 0.42, -0.05], mirror = cfg[3] > 0.5;
    for (let i = 0; i < N; i++) {
      const sp = 0.036 + 0.024 * ((i * 7) % 5) / 4, ph = ((i / N) + tm * sp) % 1, yy = ph;
      let cx = asp * (cfg[0] + cfg[1] * yy * yy + cfg[2] * Math.sin(yy * Math.PI)) + 0.04 * asp * Math.sin(t * 0.6 + yy * 2.0); if (mirror) cx = asp - cx;
      const hw = asp * (0.075 + 0.17 * yy) * w, x = ((cx + D[i % D.length] * hw) / asp) * W, y = yy * H;
      let fade = Math.min(1, ph / 0.08, (1 - ph) / 0.08, (W - 150 - x) / 90, (x - 10) / 60);
      const cw = els[i].offsetWidth || 120, av = canvas._avoid || [];
      for (let k = 0; k < av.length; k++) { const a = av[k]; if (y > a.top && y < a.bottom && x + cw > a.left && x < a.right) { fade = 0; break; } }
      const el = els[i]; el.style.transform = 'translate3d(' + Math.round(x) + 'px,' + Math.round(y) + 'px,0)'; el.style.opacity = Math.max(0, fade).toFixed(2);
    }
  }

  gradRef = (el) => { if (!this.streams) this.streams = new Map(); if (!el || this.streams.has(el)) return; const inst = this.startGradient(el); if (inst) this.streams.set(el, inst); };

  stopGradient() { if (this.streams) { this.streams.forEach((i) => i.cleanup()); this.streams.clear(); } }

  startGradient(canvas) {
    let gl = null; try { gl = canvas.getContext('webgl', { antialias: false, alpha: true, premultipliedAlpha: true, depth: false, powerPreference: 'low-power' }); } catch (e) {}
    if (!gl) return;
    const vs = 'attribute vec2 a;void main(){gl_Position=vec4(a,0.,1.);}';
    const fs = 'precision mediump float;uniform float u_time;uniform float u_px;uniform float u_w;uniform float u_mode;uniform float u_scroll;uniform float u_vh;uniform vec2 u_mouse;uniform float u_hole;uniform vec4 u_cfg;uniform vec2 u_res;uniform vec3 u_c0,u_c1,u_c2,u_c3,u_c4,u_c5;' +
      'vec3 mod289(vec3 x){return x-floor(x*(1.0/289.0))*289.0;}vec2 mod289(vec2 x){return x-floor(x*(1.0/289.0))*289.0;}vec3 permute(vec3 x){return mod289(((x*34.0)+1.0)*x);}' +
      'float snoise(vec2 v){const vec4 C=vec4(0.211324865405187,0.366025403784439,-0.577350269189626,0.024390243902439);vec2 i=floor(v+dot(v,C.yy));vec2 x0=v-i+dot(i,C.xx);vec2 i1=(x0.x>x0.y)?vec2(1.0,0.0):vec2(0.0,1.0);vec4 x12=x0.xyxy+C.xxzz;x12.xy-=i1;i=mod289(i);vec3 p=permute(permute(i.y+vec3(0.0,i1.y,1.0))+i.x+vec3(0.0,i1.x,1.0));vec3 m=max(0.5-vec3(dot(x0,x0),dot(x12.xy,x12.xy),dot(x12.zw,x12.zw)),0.0);m=m*m;m=m*m;vec3 x=2.0*fract(p*C.www)-1.0;vec3 h=abs(x)-0.5;vec3 ox=floor(x+0.5);vec3 a0=x-ox;m*=1.79284291400159-0.85373472095314*(a0*a0+h*h);vec3 g;g.x=a0.x*x0.x+h.x*x0.y;g.yz=a0.yz*x12.xz+h.yz*x12.yw;return 130.0*dot(m,g);}' +
      'float hash(vec2 q){return fract(sin(dot(q,vec2(127.1,311.7)))*43758.5453);}' +
      'vec3 across(float k){vec3 c=mix(u_c4,u_c0,smoothstep(0.0,0.3,k));c=mix(c,u_c1,smoothstep(0.3,0.56,k));c=mix(c,u_c2,smoothstep(0.56,0.8,k));c=mix(c,u_c3,smoothstep(0.8,1.0,k));return c;}' +
      'void main(){vec2 fc=gl_FragCoord.xy;vec2 dv=fc-u_mouse;float dist=length(dv);float hole=smoothstep(u_hole+1.0,0.0,dist);fc+=normalize(dv+vec2(0.001,0.0))*u_hole*0.85*hole*hole;vec2 cell=floor(fc/u_px);vec2 cc=(cell+0.5)*u_px;vec2 uv=cc/u_res;float asp=u_res.x/u_res.y;vec2 p=vec2(uv.x*asp,uv.y);float t=u_time*0.10;float yy=1.0-uv.y;' +
      'float cx=asp*(u_cfg.x+u_cfg.y*yy*yy+u_cfg.z*sin(yy*3.14159))+0.04*asp*sin(t*0.6+yy*2.0)+0.05*asp*snoise(vec2(yy*1.4+t*0.25,3.1));cx=mix(cx,asp-cx,u_cfg.w);' +
      'float yDoc=u_scroll+(1.0-uv.y)*u_vh;float th=yDoc/2400.0*6.2832+0.18;float cxg=asp*(0.5+0.56*sin(th))+0.04*asp*sin(t*0.6+yDoc/500.0);float hwg=asp*(0.12+0.03*sin(th*2.0));' +
      'cx=mix(cx,cxg,u_mode);float hw=mix(asp*(0.075+0.17*yy)*u_w,hwg,u_mode);float yA=mix(yy,yDoc/max(u_vh,1.0),u_mode);float dim=mix(1.0,mix(1.0,0.6,smoothstep(700.0,1100.0,yDoc)),u_mode);float d=(p.x-cx)/hw;float ad=abs(d);' +
      'float nl=44.0;float lane=floor((d*0.5+0.5)*nl);float lh=hash(vec2(lane,7.0));float laneOn=step(0.16,lh);' +
      'float along=yA*2.6-u_time*(0.05+0.10*lh);' +
      'float v=snoise(vec2(lane*0.9,along*4.6+lh*20.0));float stream=smoothstep(0.12,0.78,v);' +
      'float spark=step(0.80,snoise(vec2(lane*1.7+3.0,along*6.0-u_time*0.7)));' +
      'float edge=1.0-smoothstep(0.45,1.02,ad);float dith=step(hash(cell+floor(u_time*0.5)*0.0),edge*edge*1.15+0.02);' +
      'float fine=step(0.3,hash(cell*0.37+vec2(floor(along*40.0),lane)));float lit=max(stream*edge*fine,spark*edge)*dith*laneOn;' +
      'float k=clamp(d*0.5+0.5+0.15*sin(along*1.2),0.0,1.0);vec3 col=across(k);col=mix(col,vec3(1.0),spark*0.5);' +
      'vec2 f=fract(fc/u_px);float sq=step(0.22,f.x)*step(0.22,f.y);' +
      'float a=lit*sq*(0.5+0.5*stream);float base=(1.0-smoothstep(0.55,1.04,ad))*0.07*laneOn;' +
      'float rim=exp(-pow((dist-u_hole*0.62)/(u_hole*0.13+0.001),2.0))*step(1.0,u_hole);col=mix(col,vec3(1.0),0.55*rim);float alpha=min(1.0,max(a,base)*dim*(1.0-hole*hole*0.92)*(1.0+0.9*rim));gl_FragColor=vec4(col*alpha,alpha);}';
    const mk = (type, src) => { const sh = gl.createShader(type); gl.shaderSource(sh, src); gl.compileShader(sh); if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) { console.warn(gl.getShaderInfoLog(sh)); return null; } return sh; };
    const v = mk(gl.VERTEX_SHADER, vs), f = mk(gl.FRAGMENT_SHADER, fs); if (!v || !f) return;
    const prog = gl.createProgram(); gl.attachShader(prog, v); gl.attachShader(prog, f); gl.linkProgram(prog); if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) return; gl.useProgram(prog);
    const buf = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, buf); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);
    const loc = gl.getAttribLocation(prog, 'a'); gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);
    const uTime = gl.getUniformLocation(prog, 'u_time'), uRes = gl.getUniformLocation(prog, 'u_res'), uPx = gl.getUniformLocation(prog, 'u_px');
    const setColors = () => { const G = V5Logic.GRAD; [G[0], G[1], G[2], this.accent(), G[3], G[4]].forEach((hex, i) => { const c = this.hexRgb(hex); gl.uniform3f(gl.getUniformLocation(prog, 'u_c' + i), c[0] / 255, c[1] / 255, c[2] / 255); }); };
    setColors();
    const cfg = (canvas.getAttribute('data-cfg') || '0.57,0.45,0,0').split(',').map(Number); gl.uniform4f(gl.getUniformLocation(prog, 'u_cfg'), cfg[0], cfg[1], cfg[2], cfg[3]); const wScale = +(canvas.getAttribute('data-w') || 1); gl.uniform1f(gl.getUniformLocation(prog, 'u_w'), wScale); const isHero = canvas.hasAttribute('data-hero'), isGlobal = canvas.hasAttribute('data-global'); gl.uniform1f(gl.getUniformLocation(prog, 'u_mode'), isGlobal ? 1 : 0); const uScroll = gl.getUniformLocation(prog, 'u_scroll'), uVh = gl.getUniformLocation(prog, 'u_vh'), uMouse = gl.getUniformLocation(prog, 'u_mouse'), uHole = gl.getUniformLocation(prog, 'u_hole'); let smx = -9999, smy = -9999, holeR = 0;
    const reduced = this.reduced(); let visible = true, raf = 0, timer = 0, cleanup = null, cssW = 0, cssH = 0, started = false; const t0 = performance.now();
    const view = this.view || (this.view = { sy: 0, w: 0, h: 0 });
    if (!this.viewOn) { this.viewOn = true; addEventListener('scroll', () => { view.sy = window.scrollY || 0; }, { passive: true }); addEventListener('resize', () => { view.w = window.innerWidth; view.h = window.innerHeight; }); }
    let low = false, lastT = 0, frames = 0, late = 0, wait = 5000, probeAt = 0;
    const mode = (l, t) => { low = l; frames = 0; late = 0; lastT = 0; if (l) { probeAt = t + wait; wait = Math.min(wait * 2, 60000); } canvas.setAttribute('data-v5-fps', l ? '30' : '60'); };
    const pace = (t) => { if (low) { if (t >= probeAt) mode(false, t); return; } const d = lastT ? t - lastT : 0; lastT = t; if (!d || d > 250) return; frames++; if (d > 25) late++; if (frames < 90) return; if (late > 18) mode(true, t); else { frames = 0; late = 0; } };
    const schedule = () => { if (low) timer = setTimeout(() => { timer = 0; raf = requestAnimationFrame(loop); }, 26); else raf = requestAnimationFrame(loop); };
    const resize = () => { const k = 3 / 3.5; const W = Math.max(2, Math.round(cssW * k)), H = Math.max(2, Math.round(cssH * k)); if (canvas.width !== W || canvas.height !== H) { canvas.width = W; canvas.height = H; gl.viewport(0, 0, W, H); } gl.uniform1f(uPx, 3); };
    const draw = () => { resize(); const tm = (performance.now() - t0) / 1000 + 40; gl.uniform1f(uScroll, view.sy); gl.uniform1f(uVh, cssH || 1);
      if (isGlobal) { const m = this.mouse || { x: -9999, y: -9999, t: 0 }, now = performance.now(), kk = canvas.width / Math.max(1, cssW); if (smx < -5000) { smx = m.x; smy = m.y; } smx += (m.x - smx) * 0.22; smy += (m.y - smy) * 0.22; const target = (m.x > -1000 && now - m.t < 1600) ? (now - (this.pulseT || 0) < 380 ? 240 : 130) : 0; holeR += (target - holeR) * 0.12; gl.uniform2f(uMouse, smx * kk, (cssH - smy) * kk); gl.uniform1f(uHole, holeR * kk); } else { gl.uniform2f(uMouse, -9999, -9999); gl.uniform1f(uHole, 0); } if (isGlobal) this.movePointsGlobal(tm, canvas); else this.movePoints(tm, canvas, cfg, wScale, isHero); gl.uniform1f(uTime, tm); gl.uniform2f(uRes, canvas.width, canvas.height); gl.drawArrays(gl.TRIANGLES, 0, 3); };
    const loop = (t) => { raf = 0; if (!canvas.isConnected) { if (cleanup) cleanup(); if (this.streams) this.streams.delete(canvas); return; } if (!visible) return; if (t) pace(t); draw(); if (!reduced) schedule(); };
    /* the loop starts on the observer's first report, after layout */
    const ro = new ResizeObserver((en) => { const b = en[0].contentRect; cssW = b.width; cssH = b.height; if (!started) { started = true; view.sy = window.scrollY || 0; view.w = window.innerWidth; view.h = window.innerHeight; resize(); loop(); } else { resize(); draw(); } }); ro.observe(canvas);
    const io = new IntersectionObserver((en) => { visible = en[0].isIntersecting; if (visible && !raf && !timer) loop(); }); if (!isGlobal) io.observe(canvas);
    cleanup = () => { cancelAnimationFrame(raf); raf = 0; clearTimeout(timer); timer = 0; ro.disconnect(); io.disconnect(); try { const ext = gl.getExtension('WEBGL_lose_context'); if (ext) ext.loseContext(); } catch (e) {} };
    return { cleanup, setColors };
  }

  isSkipped() { return false; }

  watchShown(io, el) { io.observe(el); }

  unwatch(io, el) { io.unobserve(el); }
}
window.V5Logic = V5Logic;
