/* Every sentence the workshop shows, in one place.
 *
 * Owner, 16.9.2026: build the functions first, put the texts in as they come,
 * all texts of the site get one pass at the end. So this file is provisional
 * by design and the only file that pass has to touch. The pattern is the
 * site's own: "Sie", short sentences, a technical term followed by what it
 * means for the reader, numbers only where the page really produces them
 * (those are filled in by the modules, never written here). */
export const T = {
  brand: "Tools",
  title: "Diese Seite von innen",
  views: { roentgen: "Röntgen", crawler: "Google & KI" },
  close: "Tools schließen",
  resetAll: "Alles zurücksetzen",
  resetAllHint: "Stellt Änderungen an Text, HTML und Reglern in umgekehrter Reihenfolge wieder her.",
  nothingStored: "Nichts wird gespeichert. Gesendet wird nur, was Sie im Tab „Fragen“ fragen.",
  tabs: { element: "Element", tree: "Baum", code: "Code", perf: "Messwerte", knobs: "Regler" },

  pick: {
    start: "Wählen",
    stop: "Fertig",
    hint: "Fahren Sie über die Seite: die Linse zeigt den Bauplan, ein Klick wählt das Element. Escape beendet die Auswahl.",
    touchHint: "Tippen Sie auf ein Element der Seite, um es zu wählen.",
    none: "Noch kein Element gewählt.",
    noneHint: "Wählen Sie eines auf der Seite oder im Baum. Danach sehen Sie hier seinen HTML-Code, die CSS-Regeln, die auf es zutreffen, und die Funktion, die es bewegt.",
  },

  element: {
    path: "Pfad",
    html: "HTML dieses Elements",
    htmlWhy: "Das ist der Knoten, wie er jetzt im Speicher des Browsers liegt, nicht wie er vom Server kam. Kinder sind eingeklappt, damit Sie die Struktur sehen statt eines Textbergs.",
    template: "Vorlage",
    templateWhy: "Eine Bindung verbindet einen Ausdruck der Vorlage ({{ }}, ein Attribut, eine Stil-Eigenschaft, ein Ereignis) mit genau diesem Element. Nach jeder Zustandsänderung wertet die Laufzeit alle Ausdrücke neu aus und schreibt nur, was sich seit dem letzten Durchlauf geändert hat, statt die Seite neu zu zeichnen: bei rund 500–700 Ausdrücken je Seite kostet ein Durchlauf dadurch nur 1–2 ms statt 64–84 ms für ein volles Rerender (tools/reactprof.mjs, 4x CPU).",
    templateNone: "Dieser Knoten stammt nicht aus der Vorlage: entweder hat ihn der Build eingefügt oder ein Skript hat ihn zur Laufzeit erzeugt.",
    templateTid: "Vorlagen-Id",
    templateAttrs: "Dynamische Attribute",
    templateStyle: "Dynamischer Stil",
    templateEvents: "Ereignisse",
    templateRef: "ref",
    templateNoDyn: "Keine dynamischen Attribute.",
    templateNoStyle: "Keine dynamischen Stil-Eigenschaften.",
    templateNoEvents: "Keine Ereignisse.",
    css: "CSS-Regeln, die zutreffen",
    cssWhy: "Der Browser prüft für dieses Element jede Regel der Seite. Hier stehen die passenden, die stärkste zuerst. Durchgestrichene Werte wurden von einer stärkeren Regel überschrieben. Ausgegraut ist eine Medienbedingung, die gerade nicht gilt.",
    cssNone: "Keine Regel der Seite trifft auf dieses Element zu. Es erbt alles von seinen Eltern.",
    computed: "Berechnete Werte",
    computedWhy: "Was am Ende gilt, nach allen Regeln und dem Erben von den Eltern. Das sind die Zahlen, mit denen der Browser zeichnet.",
    box: "Box-Modell",
    boxWhy: "Jedes Element ist ein Kasten mit vier Schichten: Inhalt, Innenabstand (padding), Rahmen (border), Außenabstand (margin). Die Linse färbt sie in denselben Farben.",
    a11y: "Barrierefreiheit",
    a11yWhy: "Ein Screenreader liest nicht das Design, sondern Rolle und Namen. Ein Knopf ohne Namen ist für ihn nur „Knopf“. Der Kontrast ist nach WCAG berechnet: ab 4,5:1 gilt normaler Text als gut lesbar (AA), ab 7:1 als sehr gut (AAA).",
    code: "Im Code",
    codeWhy: "Die Karte verbindet Elemente mit den Funktionen, die sie bewegen. Ein Sprung öffnet die Datei an der Stelle der Funktion.",
    codeNone: "Für dieses Element läuft kein eigenes Skript. Es ist reines HTML und CSS, und genau das ist schnell.",
    edit: "Ändern",
    editWhy: "Sie ändern nur Ihre eigene Kopie der Seite in diesem Tab. Neu laden stellt alles wieder her, „Zurücksetzen“ auch. Skripte in eingefügtem HTML werden nicht ausgeführt.",
    editText: "Text",
    editHtml: "HTML",
    apply: "Anwenden",
    reset: "Zurücksetzen",
    edited: "geändert",
    reveal: "Auf der Seite zeigen",
    skipped: "übersprungen",
    skippedHint: "Der Browser überspringt diesen Block gerade (content-visibility). Er hat weder Layout noch Stil berechnet, nur den gemessenen Platzhalter eingesetzt.",
  },

  tree: {
    title: "Der DOM-Baum",
    why: "Das Document Object Model ist die Seite, wie der Browser sie im Speicher hält: ein Baum aus Knoten. Was Sie sehen, ist die Zeichnung dieses Baums. Fahren Sie über eine Zeile, um den Knoten auf der Seite zu sehen; ein Klick wählt ihn.",
    expand: "aufklappen",
    collapse: "zuklappen",
    text: "Text",
    more: "weitere",
    stats: (n, d) => `${n} Elemente, ${d} Ebenen tief`,
  },

  code: {
    title: "Der Code dieser Seite",
    why: "Alles, was diese Seite kann, steht in diesen Dateien. Es gibt kein Framework, das zur Laufzeit dazwischen liegt: handgeschriebenes HTML, CSS und wenig JavaScript. Das ist der Grund, warum sie so schnell lädt.",
    search: "Im Code suchen",
    lines: "Zeilen",
    loading: "wird geladen …",
    failed: "konnte nicht geladen werden",
    jumpTo: "Zur Funktion",
    files: {
      "html-live": {
        name: "index.html · jetzt im Browser",
        what: "Der komplette Baum, wie er in diesem Moment im Speicher liegt, inklusive allem, was Skripte seit dem Laden verändert haben.",
        why: "Der Vergleich mit der Fassung vom Server zeigt, wie wenig JavaScript an dieser Seite noch ändern muss.",
      },
      html: {
        name: "index.html · vom Server",
        what: "Die Datei, die Ihr Browser als Erstes bekommen hat: fertiges HTML mit allem Text, den Stilen und den Vorlagen.",
        why: "Weil alles schon drinsteht, kann der Browser sofort zeichnen und ein Crawler alles lesen, ohne ein Skript auszuführen.",
      },
      css: {
        name: "style#v5-css",
        what: "Das Stylesheet der Seite, im HTML eingebettet statt als eigene Datei.",
        why: "Eine eigene CSS-Datei wäre ein zweiter Netzwerk-Umweg vor dem ersten Bild. Eingebettet steht sie im selben Paket wie das HTML.",
      },
      runtime: {
        name: "runtime.js",
        what: "Das Verhalten jeder v5-Seite ohne React: Es bindet die mitgelieferte Vorlage ans schon fertig gerenderte HTML und schreibt nach jeder Zustandsänderung nur, was sich wirklich geändert hat.",
        why: "React renderte bei jeder Zustandsänderung die ganze Seite neu: 15 volle Durchläufe in 30 s bei 64–84 ms je Durchlauf (gemessen 16.9.2026 mit Reacts Profiling-Build, 4x CPU). Der Binder kostet dafür rund 1–2 ms. Ausgeliefert wird die verdichtete Fassung; hier lesen Sie die kommentierte Quelle.",
      },
      logic: {
        name: "logic.gen.js",
        what: "Die Funktionen der Seite: der Strom im Hintergrund, Zähler, das Prozess-Rail, die Datenfluss-Grafik.",
        why: "Sie stammen aus der Entwurfsdatei und werden beim Bauen wörtlich kopiert; der Entwurf bleibt die einzige Quelle. Ausgeliefert wird die verdichtete Fassung, hier lesen Sie die Quelle.",
      },
      motion: {
        name: "motion-budget.js",
        what: "Pausiert Endlos-Animationen, die gerade niemand sieht, und startet sie erst, wenn ihr Block ins Bild kommt.",
        why: "Jede laufende Animation kostet Rechenzeit, auch unsichtbar. Die ausgelieferte Fassung ist verdichtet; hier lesen Sie die kommentierte Quelle.",
      },
      "shader-frag": {
        name: "Strom · Fragment-Shader (GLSL)",
        what: "Das Programm, das die Grafikkarte für jeden Bildpunkt des Hintergrunds ausführt: Rauschen, Farbverlauf, das Loch um die Maus.",
        why: "Auf der Grafikkarte kosten Millionen Bildpunkte pro Bild fast nichts. Auf dem Hauptprozessor wäre dieselbe Fläche unbezahlbar.",
      },
      "shader-vert": {
        name: "Strom · Vertex-Shader (GLSL)",
        what: "Drei Eckpunkte, ein Dreieck, das den ganzen Bildschirm überdeckt. Mehr Geometrie braucht der Strom nicht.",
        why: "Ein einziges Dreieck ist der billigste Weg, jeden Bildpunkt einmal zu berühren.",
      },
      heights: {
        name: "style#v5-cv-heights",
        what: "Die gemessene Höhe jedes aufgeschobenen Blocks bei sechs Fensterbreiten.",
        why: "Ein Block, den der Browser überspringt, braucht einen Platzhalter in der richtigen Höhe. Sonst springt die Seite beim ersten Scrollen um tausende Pixel.",
      },
      map: {
        name: "map.json · Karte Element → Code",
        what: "Die handgepflegte Verbindung zwischen Seitenelementen und den Funktionen, die sie bewegen.",
        why: "Ohne diese Karte müssten Sie raten, wo ein Verhalten herkommt. Mit ihr ist jeder Sprung im Tab „Element“ ein Klick.",
      },
      dev: {
        name: "Die Tools selbst",
        what: "Der Code, der gerade läuft, damit Sie das hier lesen können.",
        why: "Er kommt sieben Sekunden nach Ihrer ersten Aktion auf der Seite. Davor kostet er die Seite kein Byte, und Messwerkzeuge, die nie klicken, sehen ihn nie.",
      },
    },
  },

  perf: {
    title: "Messwerte dieses Besuchs",
    why: "Keine Laborwerte, keine Behauptungen: Ihr Browser hat diese Zeiten selbst gemessen, während die Seite lud. Auf einem anderen Gerät oder Netz sehen sie anders aus.",
    timeline: "Zeitachse",
    timelineWhy: "TTFB ist das erste Byte vom Server. FCP der erste sichtbare Inhalt. LCP das größte Element im Bild, bei Google die wichtigste Zahl: unter 2,5 s gilt als gut.",
    ttfb: "Erstes Byte",
    fcp: "Erster Inhalt",
    lcp: "Größtes Element",
    dcl: "HTML verarbeitet",
    load: "Alles geladen",
    lcpEl: "Das größte Element",
    lcpWhy: "Google misst, wann das größte sichtbare Element fertig gezeichnet war. Auf dieser Seite ist das Text, kein Bild. Text ist da, sobald die Schrift da ist, und die Schrift kommt mit dem ersten Paket.",
    cls: "Layout-Sprünge",
    clsWhy: "Wenn Inhalt nachrückt und alles darunter verschiebt, ist das ein Layout-Sprung. Google summiert sie zum CLS; unter 0,1 gilt als gut. Jeder Eintrag zeigt, welcher Knoten sich bewegt hat.",
    clsNone: "Kein Layout-Sprung gemessen. Nichts hat sich unter Ihrem Finger oder Zeiger verschoben.",
    longtasks: "Lange Aufgaben",
    longtasksWhy: "Eine Aufgabe über 50 ms blockiert den Hauptthread: solange reagiert die Seite nicht auf Eingaben. Google nennt die Summe der Überhänge nach dem ersten Inhalt „Total Blocking Time“.",
    longtasksNone: "Keine Aufgabe über 50 ms. Die Seite war jederzeit ansprechbar.",
    transfer: "Übertragung",
    transferWhy: "Die Seite reist komprimiert. Was der Browser entpackt, ist ein Vielfaches dessen, was durch die Leitung ging.",
    resources: "Ressourcen",
    resourcesWhy: "Jeder Balken ist eine Datei, von der Anfrage bis zum letzten Byte, auf einer gemeinsamen Zeitachse. Wenig Dateien, früh angefragt, ist die ganze Kunst.",
    fromCache: "aus dem Cache",
    fps: "Bildrate",
    fpsWhy: "Ihr Browser zeichnet die Seite so oft pro Sekunde. Der Strom im Hintergrund misst sich selbst und schaltet auf 30 Bilder, wenn das Gerät nicht hinterherkommt, statt zu ruckeln.",
    fpsStream: "Strom",
    fpsMode: (m) => (m ? `${m} Bilder/s` : "60 Bilder/s, nie gedrosselt"),
    cv: "Übersprungene Blöcke",
    cvWhy: "Blöcke unterhalb des Bildschirms trägt der Browser als Platzhalter ein und rechnet sie erst durch, wenn sie näher kommen (content-visibility). Diese Liste ändert sich, während Sie scrollen.",
    cvRendered: "gerendert",
    cvSkipped: "übersprungen",
    cvPlaceholder: "Platzhalter",
    animations: "Animationen",
    animationsWhy: "Jede laufende Animation kostet Rechenzeit, auch außerhalb des Bildes. Das Motion-Budget der Seite hält Endlosschleifen an, bis ihr Block sichtbar ist.",
    running: "laufend",
    paused: "angehalten",
    held: "Motion-Budget hält noch",
    dom: "Dokument",
    domWhy: "Weniger Knoten heißt weniger Arbeit bei jedem Stil- und Layout-Durchlauf. Google warnt ab 1.500 Elementen; diese Seite schiebt einen Teil davon als Vorlagen mit, die erst bei Bedarf in den Baum kommen.",
    device: "Ihr Gerät und Netz",
    deviceWhy: "Diese Werte erklären die anderen. Dieselbe Seite lädt auf einem alten Telefon im Funkloch anders als hier.",
    cores: "Prozessorkerne",
    memory: "Arbeitsspeicher",
    connection: "Verbindung",
    dpr: "Pixeldichte",
    viewport: "Fenster",
    gpu: "Grafik",
    reduced: "Bewegung reduzieren",
    pointer: "Eingabe",
    heap: "JS-Speicher",
    unknown: "nicht verfügbar",
    yes: "an",
    no: "aus",
    coarse: "Touch",
    fine: "Maus oder Stift",
  },

  knobs: {
    title: "Regler",
    why: "Nur Regler, die auf der Seite etwas Echtes umstellen. Was hier fehlt, existiert in der Seite nicht als Stellschraube, und das sehen Sie dann auch.",
    accent: "Akzentfarbe",
    accentWhy: "Die Seite hat genau vier Farbvariablen (--acc und drei Ableitungen). Was daran hängt, dreht mit. Was fest eingebrannt ist, bleibt: so sieht man, wo einem Designsystem noch Variablen fehlen.",
    accentHue: "Farbton",
    motion: "Bewegung reduzieren",
    motionWhy: "Dieselbe Regel, die die Seite anwendet, wenn Ihr System „Bewegung reduzieren“ verlangt: Animationen enden nach einem Bild. Der Strom prüft die Einstellung nur beim Start; ihn hält ein Neuladen an.",
    font: "Schrift-Fallback zeigen",
    fontWhy: "So sähe die Seite aus, wenn die eigene Schrift nicht käme oder Sie sie abgestellt hätten. Der Browser zeigt sofort die Systemschrift und tauscht später (font-display: swap).",
    placeholders: "Platzhalter zeigen",
    placeholdersWhy: "Die Umrisse der aufgeschobenen Blöcke mit ihrem Zustand. Scrollen Sie, und sehen Sie, wie der Browser Blöcke rendert und wieder überspringt.",
    reset: "Zurücksetzen",
  },

  crawler: {
    title: "Wie Google und Sprachmodelle diese Seite lesen",
    why: "Warum das gut ist",
    head: "Kopfzeilen",
    headWhy: "Title und Description sind die zwei Zeilen im Suchergebnis. Der Canonical sagt, welche Adresse die eine gültige ist. „robots“ steuert, ob die Seite in den Index darf: diese Vorschau ist bewusst auf noindex, bis sie die Startseite ersetzt.",
    headers: "Antwort des Servers",
    headersWhy: "Auch die Kopfzeilen der Antwort sind Signale: Kompression, Cache-Regeln, die Sicherheitsrichtlinie (CSP) und X-Robots-Tag. Ein Crawler liest sie vor dem ersten Byte HTML.",
    headings: "Überschriften-Baum",
    headingsWhy: "Überschriften sind das Inhaltsverzeichnis für Maschinen: genau eine h1, darunter h2 für Abschnitte, h3 für Unterpunkte, ohne Sprünge. Ein Sprachmodell nutzt dieselbe Gliederung, um Antworten zu belegen.",
    headingsOk: "Genau eine h1, keine übersprungene Ebene.",
    landmarks: "Landmarken",
    landmarksWhy: "header, nav, main und footer sagen einem Screenreader und einem Crawler, was Navigation ist und was Inhalt. Der Skip-Link lässt Tastaturnutzer die Navigation überspringen.",
    images: "Bilder",
    imagesWhy: "Ein alt-Text ist das Bild für alle, die es nicht sehen: Screenreader, Crawler, langsame Netze. Ein leeres alt sagt „dekorativ, überspringen“. width und height reservieren den Platz, bevor das Bild da ist.",
    imagesMissingSize: "ohne width/height",
    links: "Links",
    linksWhy: "Der Ankertext ist das, was Google über das Ziel lernt. „Hier klicken“ lehrt nichts. Interne Links verteilen die Gewichtung im Angebot; externe sagen, wem man vertraut.",
    internal: "intern",
    external: "extern",
    anchors: "Sprungmarken",
    emptyAnchors: "ohne Text",
    jsonld: "Strukturierte Daten",
    jsonldWhy: "JSON-LD nach schema.org sagt in Maschinensprache, wer hier spricht und was angeboten wird. Google zeigt daraus Rich Results, etwa aufklappbare Fragen. Ein Sprachmodell bekommt Fakten statt Fließtext.",
    markdown: "Markdown-Zwilling",
    markdownWhy: "Dieselbe Seite als reiner Text mit Gliederung - der Zwilling liegt als index.md neben jeder Seite. Ein Sprachmodell liest sie ohne HTML-Rauschen, mit einem Zehntel der Tokens. Der Zwilling wird beim Bauen erzeugt, nie von Hand.",
    markdownMissing: "Noch kein Markdown-Zwilling unter dieser Adresse.",
    llms: "llms.txt",
    llmsWhy: "Ein Vorschlag von llmstxt.org: eine Datei, die Sprachmodellen sagt, was diese Site ist und welche Seiten sich lohnen. Sie liegt unter /llms.txt.",
    robots: "robots.txt",
    robotsWhy: "Hier steht, wer crawlen darf. Diese Site erlaubt KI-Crawler ausdrücklich, jeden mit eigener Gruppe, und sperrt nur die Entwurfsdateien und den Frage-Endpunkt der Tools.",
    robotsAllowed: "Ausdrücklich erlaubt",
    sitemap: "sitemap.xml",
    sitemapWhy: "Die Liste aller Seiten mit Änderungsdatum. Sie wird beim Bauen aus derselben Tabelle erzeugt wie die Navigation und kann deshalb nicht daneben liegen.",
    sitemapNotIn: "Diese Vorschau steht noch nicht in der Sitemap.",
    text: "Lesbarer Text",
    textWhy: "Was übrig bleibt, wenn man alles außer Text entfernt. Das ist der Rohstoff, aus dem eine Suchmaschine Bedeutung zieht.",
    words: "Wörter",
    readMin: "Minuten Lesezeit",
    show: "anzeigen",
    hide: "verbergen",
    more: "mehr",
    less: "weniger",
    loading: "wird geladen …",
    missing: "fehlt",
    chars: "Zeichen",
    lengthOk: "gute Länge",
    tooLong: "eher lang",
    tooShort: "eher kurz",
  },
  /* ---- Die Konsole (17.9.2026): Andocken, Griff, Leitzeilen, Statuszeile,
   * Rundgang, Glossar und die Sicht „Fragen“. Vorläufig wie alles hier. */
  dock: {
    bottom: "Unten",
    right: "Rechts",
    float: "Fenster",
    bottomHint: "Konsole unten andocken: volle Breite, die Seite bleibt darüber sichtbar.",
    rightHint: "Konsole rechts andocken: eine Spalte neben der Seite.",
    floatHint: "Konsole als freies Fenster: am Kopf ziehen, an der rechten Kante, der unteren Kante oder der Ecke die Größe ändern.",
    moveHint: "Ziehen bewegt das Fenster. Mit der Tastatur: Pfeiltasten bewegen, Shift + Pfeiltasten ändern die Größe, Pos1 setzt zurück.",
    grip: "Größe der Konsole",
    gripHint: "Ziehen ändert die Größe, Doppelklick wechselt zwischen voller Größe und zurück. Mit der Tastatur: Pfeiltasten, Pos1, Ende.",
    closeHint: "Schließt die Tools und stellt die Seite wieder her. Escape tut dasselbe.",
  },
  keys: "Esc schließt · ← → wechseln die Tabs · Griff ziehen oder ↑ ↓ ändert die Größe",
  keysFloat: "Esc schließt · Kopf ziehen bewegt · Kante oder Ecke ziehen ändert die Größe · Pfeile am Titel bewegen, Shift + Pfeile skalieren",
  status: {
    ready: "Bereit. Nichts wird gespeichert. Gesendet wird nur, was Sie im Tab „Fragen“ fragen.",
    selected: (label, rules, code) => `${label} gewählt · ${rules} CSS-${rules === 1 ? "Regel" : "Regeln"} · ${code ? `Code: ${code}` : "kein eigenes Skript"}`,
    picking: "Auswahl läuft: fahren Sie über die Seite und klicken Sie ein Element. Escape bricht ab.",
    pickStopped: "Auswahl beendet.",
    tab: (name) => `Tab „${name}“`,
    file: (name, lines) => `${name} geöffnet · ${lines} Zeilen`,
    edits: (n) => (n ? `${n} ${n === 1 ? "Änderung" : "Änderungen"} in dieser Kopie der Seite. Neu laden stellt alles wieder her.` : "Alle Änderungen zurückgenommen."),
    docked: (where) => (where === "bottom" ? "Konsole unten angedockt." : where === "right" ? "Konsole rechts angedockt." : "Konsole als freies Fenster."),
    moved: (x, y, w, hh) => `Fenster bei ${x}, ${y} · ${w} × ${hh} px.`,
    size: (px, full, axis) => (full ? (axis === "w" ? "Konsole auf voller Breite." : "Konsole auf voller Höhe.") : axis === "w" ? `Konsole ${px} px breit.` : `Konsole ${px} px hoch.`),
    view: { roentgen: "Röntgen: die Seite von innen.", crawler: "Google & KI: wie Maschinen diese Seite lesen.", ask: "Fragen: Claude antwortet mit den Fakten dieser Seite." },
    asked: "Antwort von Claude.",
    askedLocal: "Antwort aus der Seite selbst, Claude war nicht erreichbar.",
  },
  leads: {
    element: "Ein Element der Seite von innen: sein HTML, die CSS-Regeln, die zutreffen, die Vorlage dahinter und der Code, der es bewegt.",
    tree: "Der ganze DOM-Baum, wie der Browser ihn im Speicher hält. Eine Zeile berühren zeigt den Knoten auf der Seite, ein Klick wählt ihn.",
    code: "Alle Dateien dieser Seite im Klartext, mit Suche und Sprung zur Funktion. Es gibt kein Framework, das dazwischenliegt.",
    perf: "Die Zeiten, die Ihr Browser bei diesem Besuch selbst gemessen hat: Laden, Zeichnen, Layout-Sprünge, lange Aufgaben.",
    knobs: "Regler, die auf der Seite etwas Echtes umstellen. Alles gilt nur in diesem Tab und lässt sich zurücksetzen.",
    crawler: "Ein Crawler sieht kein Design. Er liest Text, Struktur und Metadaten, in dieser Reihenfolge. Jede Station zeigt, was er findet.",
    ask: "Stellen Sie Fragen zu dieser Seite. Claude bekommt dazu die Fakten aus den Tools und den Text der Seite, sonst nichts.",
  },
  tour: {
    title: "So funktionieren die Tools",
    steps: [
      ["Wählen", "Drücken Sie „Wählen“ und klicken Sie ein Element auf der Seite. Oder öffnen Sie den Tab „Baum“ und wählen dort."],
      ["Lesen", "Der Tab „Element“ zeigt dann sein HTML, die CSS-Regeln, die Vorlage und den Code, der es bewegt. Jede Karte sagt unter „Warum das gut ist“, was Sie sehen."],
      ["Weiter", "„Messwerte“ zeigt die Zeiten dieses Besuchs, „Google & KI“, wie Maschinen die Seite lesen, und unter „Fragen“ antwortet Claude."],
    ],
    hint: "Begriffe mit gepunkteter Linie erklären sich per Klick. Die Statuszeile unten sagt zu jedem Knopf, was er tut.",
  },
  hints: {
    pick: "Wählen Sie ein Element direkt auf der Seite. Escape beendet die Auswahl.",
    reveal: "Scrollt die Seite zum gewählten Element und hebt es kurz hervor.",
    up: "Wählt das Elternelement.",
    resetAll: "Nimmt alle Änderungen an Text, HTML und Reglern zurück, in umgekehrter Reihenfolge.",
    viewRoentgen: "Element, Baum, Code, Messwerte und Regler.",
    viewCrawler: "Stationen: Kopfzeilen, Überschriften, Bilder, Links, strukturierte Daten, Markdown-Zwilling.",
    viewAsk: "Fragen an Claude, mit den Fakten dieser Seite.",
    wrap: "Lange Zeilen umbrechen statt waagerecht zu scrollen.",
    search: "Sucht im geöffneten Text. Enter springt zum nächsten Treffer.",
    next: "Zum nächsten Treffer.",
    file: "Öffnet die Datei im Betrachter.",
    codeJump: "Öffnet die Datei an der Stelle der Funktion.",
    apply: "Übernimmt den Text in Ihre Kopie der Seite. Nichts verlässt den Browser.",
    reset: "Stellt dieses Element wieder her.",
    editText: "Nur den Text ändern.",
    editHtml: "Das ganze HTML des Elements ändern.",
    accentReset: "Zurück zur Akzentfarbe der Seite.",
    treeRow: "Klick wählt den Knoten, Pfeiltasten bewegen sich im Baum.",
    lcpOpen: "Öffnet das größte Element im Tab „Element“.",
    showText: "Zeigt den Text, den ein Crawler aus dieser Seite zieht.",
    codeScroll: "Klicken Sie in den Code, dann scrollt er. Ein Klick daneben gibt das Scrollen an die Konsole zurück.",
    codeScrollShort: "Klicken zum Scrollen",
  },
  glossar: {
    LCP: "Largest Contentful Paint: der Moment, in dem das größte sichtbare Element fertig gezeichnet ist. Für Google die wichtigste Ladezeit, unter 2,5 Sekunden gilt als gut.",
    FCP: "First Contentful Paint: der Moment, in dem der erste Inhalt auf dem Bildschirm erscheint, ein Text oder ein Bild.",
    TTFB: "Time to First Byte: die Zeit vom Abschicken der Anfrage bis zum ersten Byte der Antwort des Servers.",
    CLS: "Cumulative Layout Shift: die Summe aller Layout-Sprünge, bei denen Inhalt nachrückt und alles darunter verschiebt. Unter 0,1 gilt als gut.",
    TBT: "Total Blocking Time: wie lange der Hauptthread nach dem ersten Inhalt blockiert war. Solange reagiert die Seite nicht auf Eingaben.",
    Hauptthread: "Der eine Faden im Browser, der Skripte ausführt, Layout rechnet und Eingaben verarbeitet. Ist er beschäftigt, steht die Seite.",
    "content-visibility": "Eine CSS-Eigenschaft: der Browser überspringt Layout und Zeichnen eines Blocks, bis er in die Nähe des Bildschirms kommt, und setzt bis dahin einen Platzhalter in gemessener Höhe.",
    CSP: "Content Security Policy: eine Kopfzeile der Antwort, die dem Browser sagt, welche Skripte, Stile und Verbindungen die Seite überhaupt laden darf.",
    Canonical: "Die eine gültige Adresse einer Seite, falls sie unter mehreren erreichbar ist. Google zählt alle Signale auf diese Adresse.",
    "JSON-LD": "Strukturierte Daten nach schema.org, als JSON im HTML. Google baut daraus Rich Results, ein Sprachmodell bekommt Fakten statt Fließtext.",
    "Rich Results": "Suchergebnisse mit Zusatz: aufklappbare Fragen, Bewertungen, Preise. Google baut sie aus strukturierten Daten.",
    WCAG: "Web Content Accessibility Guidelines: der Standard für Barrierefreiheit. AA ist die übliche Stufe, AAA die strenge.",
    DOM: "Document Object Model: die Seite als Baum aus Knoten im Speicher des Browsers. Was Sie sehen, ist die Zeichnung dieses Baums.",
    Crawler: "Ein Programm, das Seiten abruft und liest, etwa der Googlebot oder der Crawler eines Sprachmodells. Es sieht Text und Struktur, kein Design.",
    Screenreader: "Software, die die Seite vorliest. Sie liest Rolle und Namen eines Elements, nicht sein Aussehen.",
    Sprachmodell: "Ein KI-Modell wie Claude, das Text liest und erzeugt. Es liest Seiten als Text, ohne Design, und zählt in Tokens.",
    Token: "Die Einheit, in der ein Sprachmodell Text zählt, ungefähr drei Viertel eines Wortes.",
    Vorlage: "Das unsichtbare <template> im HTML: derselbe Aufbau wie die Seite, mit Ausdrücken statt Werten. Der Binder verbindet beides.",
    Binder: "Das Skript runtime.js: es liest die Vorlage, findet jeden Knoten im fertigen HTML und schreibt nach einer Zustandsänderung nur, was sich geändert hat.",
    Rerender: "Der volle Neuaufbau einer Seite durch ein Framework bei jeder Zustandsänderung. Genau das macht diese Seite nicht mehr.",
    Spezifität: "Die Rangordnung von CSS-Regeln: eine Id schlägt eine Klasse, eine Klasse schlägt einen Elementnamen, !important schlägt alles.",
    Landmarken: "HTML-Bereiche wie header, nav, main und footer, die Screenreader und Crawler als Orientierung nutzen.",
    Markdown: "Reiner Text mit einfacher Gliederung: # für Überschriften, - für Listen. Ein Sprachmodell liest ihn mit einem Zehntel der Tokens von HTML.",
    Cache: "Der Zwischenspeicher des Browsers. Was im Cache liegt, kommt beim nächsten Besuch ohne Netzwerk.",
    Brotli: "Das Kompressionsverfahren, mit dem der Server diese Seite verschickt. Was durch die Leitung geht, ist ein Bruchteil dessen, was der Browser entpackt.",
  },
  ask: {
    view: "Fragen",
    title: "Fragen Sie diese Seite",
    privacy: "Ihre Frage geht zusammen mit den Fakten dieser Seite an Claude, nicht an uns. Kein Verlauf wird gespeichert, weder hier noch dort.",
    placeholder: "Zum Beispiel: Warum lädt diese Seite so schnell?",
    send: "Fragen",
    sendHint: "Schickt die Frage mit den Fakten aus den Tools an Claude.",
    thinking: "Claude liest die Fakten …",
    offline: "Claude ist gerade nicht erreichbar. Das ist eine Antwort aus der Seite selbst, ohne Modell.",
    offlinePill: "ohne Claude",
    fromClaude: "Claude",
    fromLocal: "Tools",
    you: "Sie",
    suggestions: ["Warum lädt diese Seite so schnell?", "Was macht das gewählte Element?", "Was bedeutet LCP?", "Wie liest Google diese Seite?", "Was würde die Seite langsamer machen?"],
    facts: "Was Claude sieht",
    factsWhy: "Genau diese Fakten gehen mit Ihrer Frage mit: die Messwerte dieses Besuchs, das gewählte Element, die Kopfzeilen und der Text der Seite als Markdown. Nichts über Sie, kein Verlauf über diesen Tab hinaus.",
    tooLong: "Bitte kürzer fragen, höchstens 600 Zeichen.",
    error: "Das ging nicht",
    clear: "Verlauf leeren",
    clearHint: "Leert die Unterhaltung in diesem Tab.",
    noSelection: "kein Element gewählt",
    factPage: "Seite",
    factSelected: "Gewähltes Element",
    factPerf: "Messwerte",
    factCrawler: "Für Crawler",
    factText: "Seitentext",
    factTextVal: (n) => `Markdown-Zwilling, ${n.toLocaleString("de-DE")} Zeichen`,
    factDevice: "Gerät",
    local: {
      fast: (fcp, lcp, long) => `Ihr Browser hat gemessen: erster Inhalt nach ${fcp}, größtes Element nach ${lcp}, ${long}. Der Grund steht in der Seite selbst: fertiges HTML vom Server, Stile eingebettet, wenig JavaScript und kein Framework, das zur Laufzeit dazwischenliegt.`,
      longNone: "keine lange Aufgabe",
      longSome: (n) => `${n} lange ${n === 1 ? "Aufgabe" : "Aufgaben"}`,
      term: (key, text, value) => (value ? `${key}: ${text} Auf dieser Seite, jetzt gemessen: ${value}.` : `${key}: ${text}`),
      element: (label, rules, code) => `Gewählt ist ${label}. ${rules} CSS-${rules === 1 ? "Regel trifft" : "Regeln treffen"} zu${code ? `, und im Code steht es unter „${code}“.` : ", und es hat kein eigenes Skript: reines HTML und CSS, und genau das ist schnell."} Mehr steht im Tab „Element“.`,
      noElement: "Es ist noch kein Element gewählt. Drücken Sie „Wählen“ und klicken Sie eines auf der Seite, dann kann ich es erklären.",
      crawler: (title, h1, heads, ld) => `Google liest zuerst den Titel „${title}“, dann die Überschriften: ${h1} h1 und ${heads} Überschriften insgesamt${ld ? `, dazu strukturierte Daten vom Typ ${ld}` : ""}. Der Tab „Google & KI“ zeigt jede Station.`,
      slower: "Langsamer würde die Seite durch alles, was vor dem ersten Bild wartet: fremde Schriften, Skripte im Kopf, ein Framework, das sie bei jeder Änderung neu zeichnet, Bilder ohne Maße, Animationen außerhalb des Bildes.",
      fallback: "Dazu steht in den Tools nichts. Sobald Claude erreichbar ist, kann er die Frage mit dem Text der Seite beantworten; sonst hilft info@mccain-digital.com.",
    },
  },
};
