/* English counterpart of texte.js. Same nested structure, same keys, same
 * function signatures, same array lengths — nothing added, nothing left out.
 * Whichever locale is active, T or T_EN, ui.js reads from it the same way.
 * Keep this file in lockstep with texte.js: any new key there needs a
 * translated key here. */
export const T_EN = {
  brand: "Tools",
  title: "This page, from the inside",
  views: { roentgen: "X-ray", crawler: "Google & AI" },
  close: "Close tools",
  resetAll: "Reset everything",
  resetAllHint: "Undoes changes to text, HTML, and knobs, in reverse order.",
  nothingStored: "Nothing is stored. Only what you ask in the “Ask” tab is sent.",
  tabs: { element: "Element", tree: "Tree", code: "Code", perf: "Metrics", knobs: "Knobs" },

  pick: {
    start: "Pick",
    stop: "Stop picking",
    hint: "Hover over the page: the lens shows the blueprint, a click picks the element. Escape stops picking.",
    touchHint: "Tap an element on the page to pick it.",
    none: "No element selected yet.",
    noneHint: "Pick one on the page or in the tree. Then you'll see its HTML code here, the CSS rules that apply to it, and the function that drives it.",
  },

  element: {
    path: "Path",
    html: "This element's HTML",
    htmlWhy: "This is the node as it sits in the browser's memory right now, not as it came from the server. Children are collapsed so you see the structure instead of a wall of text.",
    template: "Template",
    templateWhy: "A binding connects a template expression ({{ }}, an attribute, a style property, an event) to exactly this element. After every state change the runtime re-evaluates all expressions and writes only what changed since the last pass, instead of repainting the page: at roughly 500–700 expressions per page, a pass costs only 1–2 ms this way instead of 64–84 ms for a full rerender (tools/reactprof.mjs, 4x CPU).",
    templateNone: "This node doesn't come from the template: either the build inserted it, or a script created it at runtime.",
    templateTid: "Template ID",
    templateAttrs: "Dynamic attributes",
    templateStyle: "Dynamic style",
    templateEvents: "Events",
    templateRef: "ref",
    templateNoDyn: "No dynamic attributes.",
    templateNoStyle: "No dynamic style properties.",
    templateNoEvents: "No events.",
    css: "CSS rules that apply",
    cssWhy: "The browser checks every rule on the page against this element. Here are the ones that match, strongest first. Struck-through values were overridden by a stronger rule. Grayed out is a media condition that doesn't currently hold.",
    cssNone: "No rule on the page applies to this element. It inherits everything from its parents.",
    computed: "Computed values",
    computedWhy: "What applies in the end, after all rules and inheriting from parents. These are the numbers the browser paints with.",
    box: "Box model",
    boxWhy: "Every element is a box with four layers: content, padding, border, margin. The lens colors them the same way.",
    a11y: "Accessibility",
    a11yWhy: "A screen reader doesn't read the design, only role and name. A button with no name is just “button” to it. Contrast is calculated per WCAG: from 4.5:1, normal text counts as readable (AA); from 7:1, as very good (AAA).",
    code: "In the code",
    codeWhy: "The map links elements to the functions that drive them. A jump opens the file at the function's location.",
    codeNone: "No script of its own runs for this element. It's plain HTML and CSS, and that's exactly why it's fast.",
    edit: "Edit",
    editWhy: "You're only changing your own copy of the page in this tab. Reloading restores everything, and so does “Reset”. Scripts in pasted HTML are not executed.",
    editText: "Text",
    editHtml: "HTML",
    apply: "Apply",
    reset: "Reset",
    edited: "edited",
    reveal: "Show on page",
    skipped: "skipped",
    skippedHint: "The browser is currently skipping this block (content-visibility). It has computed neither layout nor style, only inserted the measured placeholder.",
  },

  tree: {
    title: "The DOM tree",
    why: "The Document Object Model is the page as the browser holds it in memory: a tree of nodes. What you see is a drawing of that tree. Hover a row to see the node on the page; a click selects it.",
    expand: "expand",
    collapse: "collapse",
    text: "Text",
    more: "more",
    stats: (n, d) => `${n} elements, ${d} levels deep`,
  },

  code: {
    title: "This page's code",
    why: "Everything this page can do lives in these files. No framework sits between them at runtime: hand-written HTML, CSS, and a little JavaScript. That's why it loads so fast.",
    search: "Search the code",
    lines: "lines",
    loading: "loading …",
    failed: "failed to load",
    jumpTo: "To the function",
    files: {
      "html-live": {
        name: "index.html · right now in the browser",
        what: "The complete tree as it sits in memory right now, including everything scripts have changed since load.",
        why: "Comparing it with the version from the server shows how little JavaScript still has to change on this page.",
      },
      html: {
        name: "index.html · from the server",
        what: "The file your browser received first: finished HTML with all the text, the styles, and the templates.",
        why: "Because everything is already there, the browser can paint immediately and a crawler can read all of it without running a script.",
      },
      css: {
        name: "style#v5-css",
        what: "The page's stylesheet, embedded in the HTML instead of a separate file.",
        why: "A separate CSS file would be a second network round trip before the first paint. Embedded, it travels in the same package as the HTML.",
      },
      runtime: {
        name: "runtime.js",
        what: "The behavior of every v5 page without React: it binds the shipped template to the already-rendered HTML and, after every state change, writes only what actually changed.",
        why: "React re-rendered the whole page on every state change: 15 full passes in 30 s at 64–84 ms per pass (measured September 16, 2026 with React's profiling build, 4x CPU). The binder does the same job for about 1–2 ms. What ships is the minified build; here you're reading the commented source.",
      },
      logic: {
        name: "logic.gen.js",
        what: "The page's functions: the background stream, counters, the process rail, the data-flow graphic.",
        why: "They come from the design file and are copied verbatim at build time; the design file stays the single source. What ships is the minified build; here you're reading the source.",
      },
      motion: {
        name: "motion-budget.js",
        what: "Pauses infinite animations that nobody is currently seeing, and starts them again only once their block comes into view.",
        why: "Every running animation costs compute time, even off-screen. What ships is minified; here you're reading the commented source.",
      },
      "shader-frag": {
        name: "Stream · fragment shader (GLSL)",
        what: "The program the graphics card runs for every pixel of the background: noise, gradient, the hole around the cursor.",
        why: "On the graphics card, millions of pixels per frame cost almost nothing. On the main processor, the same area would be unaffordable.",
      },
      "shader-vert": {
        name: "Stream · vertex shader (GLSL)",
        what: "Three vertices, one triangle that covers the whole screen. The stream needs no more geometry than that.",
        why: "A single triangle is the cheapest way to touch every pixel once.",
      },
      heights: {
        name: "style#v5-cv-heights",
        what: "The measured height of every deferred block at six window widths.",
        why: "A block the browser skips needs a placeholder at the right height. Otherwise the page jumps by thousands of pixels on the first scroll.",
      },
      map: {
        name: "map.json · element → code map",
        what: "The hand-maintained link between page elements and the functions that drive them.",
        why: "Without this map, you'd have to guess where a behavior comes from. With it, every jump in the “Element” tab is one click.",
      },
      dev: {
        name: "The tools themselves",
        what: "The code that's running right now so you can read this.",
        why: "It arrives seven seconds after your first action on the page. Before that, it costs the page zero bytes, and measurement tools that never click never see it.",
      },
    },
  },

  perf: {
    title: "Metrics for this visit",
    why: "No lab numbers, no claims: your browser measured these times itself while the page loaded. On a different device or network, they'd look different.",
    timeline: "Timeline",
    timelineWhy: "TTFB is the first byte from the server. FCP is the first visible content. LCP is the largest element in view, the number Google weighs most: under 2.5 s counts as good.",
    ttfb: "First byte",
    fcp: "First content",
    lcp: "Largest element",
    dcl: "HTML processed",
    load: "Everything loaded",
    lcpEl: "The largest element",
    lcpWhy: "Google measures when the largest visible element finished painting. On this page, that's text, not an image. Text is there as soon as the font is there, and the font arrives with the first package.",
    cls: "Layout shifts",
    clsWhy: "When content shifts in and pushes everything below it down, that's a layout shift. Google sums them into CLS; under 0.1 counts as good. Each entry shows which node moved.",
    clsNone: "No layout shift measured. Nothing moved under your finger or pointer.",
    longtasks: "Long tasks",
    longtasksWhy: "A task over 50 ms blocks the main thread: for that long, the page doesn't respond to input. Google calls the sum of the overhangs after first content “Total Blocking Time”.",
    longtasksNone: "No task over 50 ms. The page stayed responsive the whole time.",
    transfer: "Transfer",
    transferWhy: "The page travels compressed. What the browser unpacks is a multiple of what went through the wire.",
    resources: "Resources",
    resourcesWhy: "Each bar is a file, from request to last byte, on a shared timeline. Few files, requested early, is the whole trick.",
    fromCache: "from cache",
    fps: "Frame rate",
    fpsWhy: "That's how many times per second your browser paints the page. The background stream measures itself and switches to 30 frames if the device can't keep up, instead of stuttering.",
    fpsStream: "Stream",
    fpsMode: (m) => (m ? `${m} fps` : "60 fps, never throttled"),
    cv: "Skipped blocks",
    cvWhy: "The browser enters blocks below the fold as placeholders and only computes them once they come closer (content-visibility). This list changes as you scroll.",
    cvRendered: "rendered",
    cvSkipped: "skipped",
    cvPlaceholder: "placeholder",
    animations: "Animations",
    animationsWhy: "Every running animation costs compute time, even off-screen. The page's motion budget holds infinite loops until their block is visible.",
    running: "running",
    paused: "paused",
    held: "Motion budget still holding",
    dom: "Document",
    domWhy: "Fewer nodes means less work on every style and layout pass. Google warns above 1,500 elements; this page ships part of that count as templates that only enter the tree on demand.",
    device: "Your device and network",
    deviceWhy: "These values explain the others. The same page loads differently on an old phone with a weak signal than it does here.",
    cores: "CPU cores",
    memory: "Memory",
    connection: "Connection",
    dpr: "Pixel density",
    viewport: "Viewport",
    gpu: "Graphics",
    reduced: "Reduce motion",
    pointer: "Input",
    heap: "JS heap",
    unknown: "not available",
    yes: "on",
    no: "off",
    coarse: "Touch",
    fine: "Mouse or stylus",
  },

  knobs: {
    title: "Knobs",
    why: "Only knobs that actually change something real on the page. Whatever's missing here doesn't exist as a control in the page, and you'll see that too.",
    accent: "Accent color",
    accentWhy: "The page has exactly four color variables (--acc and three derivatives). Whatever depends on them moves with it. Whatever's hardcoded stays put: that's how you see where a design system is still missing variables.",
    accentHue: "Hue",
    motion: "Reduce motion",
    motionWhy: "The same rule the page applies when your system requests “reduce motion”: animations end after one frame. The stream checks the setting only at start; only a reload stops it.",
    font: "Show font fallback",
    fontWhy: "This is what the page would look like if its own font never arrived or you'd turned it off. The browser shows the system font immediately and swaps later (font-display: swap).",
    placeholders: "Show placeholders",
    placeholdersWhy: "The outlines of deferred blocks with their state. Scroll, and watch the browser render blocks and skip them again.",
    reset: "Reset",
  },

  crawler: {
    title: "How Google and language models read this page",
    why: "Why that's good",
    head: "Head tags",
    headWhy: "Title and description are the two lines in the search result. The canonical says which address is the one valid one. “robots” controls whether the page may enter the index: this preview is deliberately set to noindex until it replaces the home page.",
    headers: "Server response",
    headersWhy: "The response headers are signals too: compression, cache rules, the security policy (CSP), and X-Robots-Tag. A crawler reads them before the first byte of HTML.",
    headings: "Heading tree",
    headingsWhy: "Headings are the table of contents for machines: exactly one h1, then h2 for sections, h3 for subpoints, with no skipped levels. A language model uses the same outline to back up its answers.",
    headingsOk: "Exactly one h1, no skipped level.",
    landmarks: "Landmarks",
    landmarksWhy: "header, nav, main, and footer tell a screen reader and a crawler what's navigation and what's content. The skip link lets keyboard users bypass the navigation.",
    images: "Images",
    imagesWhy: "Alt text is the image for everyone who can't see it: screen readers, crawlers, slow networks. An empty alt says “decorative, skip”. width and height reserve the space before the image arrives.",
    imagesMissingSize: "missing width/height",
    links: "Links",
    linksWhy: "Anchor text is what Google learns about the destination. “Click here” teaches nothing. Internal links distribute weight across the site; external links say who you trust.",
    internal: "internal",
    external: "external",
    anchors: "Jump anchors",
    emptyAnchors: "without text",
    jsonld: "Structured data",
    jsonldWhy: "JSON-LD per schema.org says, in machine language, who's speaking here and what's on offer. Google builds rich results from it, like expandable questions. A language model gets facts instead of running text.",
    markdown: "Markdown twin",
    markdownWhy: "The same page as plain text with an outline - the twin sits as index.md next to every page. A language model reads it without HTML noise, at a tenth of the tokens. The twin is generated at build time, never by hand.",
    markdownMissing: "No markdown twin yet at this address.",
    llms: "llms.txt",
    llmsWhy: "A proposal from llmstxt.org: a file that tells language models what this site is and which pages are worth reading. It lives at /llms.txt.",
    robots: "robots.txt",
    robotsWhy: "This states who may crawl. This site explicitly allows AI crawlers, each with its own group, and blocks only the draft files and the tools' ask endpoint.",
    robotsAllowed: "Explicitly allowed",
    sitemap: "sitemap.xml",
    sitemapWhy: "The list of all pages with their change date. It's generated at build time from the same table as the navigation, so it can't drift out of sync.",
    sitemapNotIn: "This preview isn't in the sitemap yet.",
    text: "Readable text",
    textWhy: "What's left once you strip away everything but text. That's the raw material a search engine draws meaning from.",
    words: "Words",
    readMin: "minutes reading time",
    show: "show",
    hide: "hide",
    more: "more",
    less: "less",
    loading: "loading …",
    missing: "missing",
    chars: "characters",
    lengthOk: "good length",
    tooLong: "on the long side",
    tooShort: "on the short side",
  },
  /* ---- The console (9/17/2026): docking, grip, lead lines, status line,
   * tour, glossary, and the "Ask" view. Provisional like everything here. */
  dock: {
    bottom: "Bottom",
    right: "Right",
    float: "Window",
    bottomHint: "Dock the console at the bottom: full width, the page stays visible above it.",
    rightHint: "Dock the console on the right: a column beside the page.",
    floatHint: "Console as a floating window: drag the header to move, drag the right edge, bottom edge, or corner to resize.",
    moveHint: "Dragging moves the window. With the keyboard: arrow keys move, Shift + arrow keys resize, Home resets.",
    grip: "Console size",
    gripHint: "Dragging resizes, double-click toggles full size and back. With the keyboard: arrow keys, Home, End.",
    closeHint: "Closes the tools and restores the page. Escape does the same.",
  },
  keys: "Esc closes · ← → switch tabs · drag the grip or ↑ ↓ to resize",
  keysFloat: "Esc closes · drag the header to move · drag an edge or corner to resize · arrow keys on the title move, Shift + arrows scale",
  status: {
    ready: "Ready. Nothing is stored. Only what you ask in the “Ask” tab is sent.",
    selected: (label, rules, code) => `${label} selected · ${rules} CSS ${rules === 1 ? "rule" : "rules"} · ${code ? `Code: ${code}` : "no script of its own"}`,
    picking: "Picking: hover the page and click an element. Escape cancels.",
    pickStopped: "Picking stopped.",
    tab: (name) => `Tab “${name}”`,
    file: (name, lines) => `${name} opened · ${lines} lines`,
    edits: (n) => (n ? `${n} ${n === 1 ? "change" : "changes"} in this copy of the page. Reloading restores everything.` : "All changes reverted."),
    docked: (where) => (where === "bottom" ? "Console docked at the bottom." : where === "right" ? "Console docked on the right." : "Console as a floating window."),
    moved: (x, y, w, hh) => `Window at ${x}, ${y} · ${w} × ${hh} px.`,
    size: (px, full, axis) => (full ? (axis === "w" ? "Console at full width." : "Console at full height.") : axis === "w" ? `Console ${px} px wide.` : `Console ${px} px tall.`),
    view: { roentgen: "X-ray: the page from the inside.", crawler: "Google & AI: how machines read this page.", ask: "Ask: Claude answers with this page's facts." },
    asked: "Answer from Claude.",
    askedLocal: "Answer from the page itself; Claude wasn't reachable.",
  },
  leads: {
    element: "One element of the page from the inside: its HTML, the CSS rules that apply, the template behind it, and the code that drives it.",
    tree: "The whole DOM tree, as the browser holds it in memory. Touching a row shows the node on the page; a click selects it.",
    code: "All this page's files in plain text, with search and jump-to-function. No framework sits in between.",
    perf: "The times your browser measured itself during this visit: loading, painting, layout shifts, long tasks.",
    knobs: "Knobs that actually change something real on the page. Everything applies only in this tab and can be reset.",
    crawler: "A crawler sees no design. It reads text, structure, and metadata, in that order. Each stop shows what it finds.",
    ask: "Ask questions about this page. Claude gets the facts from the tools and the page's text, and nothing else.",
  },
  tour: {
    title: "How the tools work",
    steps: [
      ["Pick", "Press “Pick” and click an element on the page. Or open the “Tree” tab and pick there."],
      ["Read", "The “Element” tab then shows its HTML, the CSS rules, the template, and the code that drives it. Every card explains what you're seeing under “Why that's good”."],
      ["Next", "“Metrics” shows this visit's times, “Google & AI” shows how machines read the page, and under “Ask”, Claude answers."],
    ],
    hint: "Terms with a dotted underline explain themselves on click. The status line at the bottom says what every button does.",
  },
  hints: {
    pick: "Pick an element directly on the page. Escape stops picking.",
    reveal: "Scrolls the page to the selected element and briefly highlights it.",
    up: "Selects the parent element.",
    resetAll: "Undoes all changes to text, HTML, and knobs, in reverse order.",
    viewRoentgen: "Element, Tree, Code, Metrics, and Knobs.",
    viewCrawler: "Stops: head tags, headings, images, links, structured data, markdown twin.",
    viewAsk: "Questions for Claude, with this page's facts.",
    wrap: "Wrap long lines instead of scrolling horizontally.",
    search: "Searches the open text. Enter jumps to the next match.",
    next: "To the next match.",
    file: "Opens the file in the viewer.",
    codeJump: "Opens the file at the function's location.",
    apply: "Applies the text to your copy of the page. Nothing leaves the browser.",
    reset: "Restores this element.",
    editText: "Change only the text.",
    editHtml: "Change the element's whole HTML.",
    accentReset: "Back to the page's accent color.",
    treeRow: "Click selects the node, arrow keys move within the tree.",
    lcpOpen: "Opens the largest element in the “Element” tab.",
    showText: "Shows the text a crawler extracts from this page.",
    codeScroll: "Click into the code, then it scrolls. Clicking outside it gives scrolling back to the console.",
    codeScrollShort: "Click to scroll",
  },
  glossar: {
    LCP: "Largest Contentful Paint: the moment the largest visible element finishes painting. The most important loading number for Google; under 2.5 seconds counts as good.",
    FCP: "First Contentful Paint: the moment the first content appears on screen, a text or an image.",
    TTFB: "Time to First Byte: the time from sending the request to the first byte of the server's response.",
    CLS: "Cumulative Layout Shift: the sum of all layout shifts, where content shifts in and pushes everything below it down. Under 0.1 counts as good.",
    TBT: "Total Blocking Time: how long the main thread was blocked after first content. For that long, the page doesn't respond to input.",
    "main thread": "The single thread in the browser that runs scripts, computes layout, and processes input. When it's busy, the page freezes.",
    "content-visibility": "A CSS property: the browser skips layout and painting for a block until it comes near the screen, and until then shows a placeholder at its measured height.",
    CSP: "Content Security Policy: a response header that tells the browser which scripts, styles, and connections the page is even allowed to load.",
    Canonical: "The one valid address for a page, if it's reachable under more than one URL. Google credits all signals to this address.",
    "JSON-LD": "Structured data per schema.org, as JSON inside the HTML. Google builds rich results from it; a language model gets facts instead of running text.",
    "Rich Results": "Search results with extras: expandable questions, ratings, prices. Google builds them from structured data.",
    WCAG: "Web Content Accessibility Guidelines: the standard for accessibility. AA is the usual level, AAA the strict one.",
    DOM: "Document Object Model: the page as a tree of nodes in the browser's memory. What you see is a drawing of that tree.",
    Crawler: "A program that fetches and reads pages, such as Googlebot or a language model's crawler. It sees text and structure, not design.",
    "screen reader": "Software that reads the page aloud. It reads an element's role and name, not its appearance.",
    "language model": "An AI model like Claude that reads and generates text. It reads pages as text, without design, and counts in tokens.",
    Token: "The unit in which a language model counts text, roughly three-quarters of a word.",
    template: "The invisible <template> in the HTML: the same structure as the page, with expressions instead of values. The binder connects the two.",
    binder: "The runtime.js script: it reads the template, finds every node in the finished HTML, and after a state change writes only what changed.",
    rerender: "The full rebuild of a page by a framework on every state change. This page no longer does that.",
    specificity: "The ranking of CSS rules: an id beats a class, a class beats an element name, !important beats everything.",
    landmarks: "HTML regions like header, nav, main, and footer that screen readers and crawlers use for orientation.",
    Markdown: "Plain text with a simple outline: # for headings, - for lists. A language model reads it at a tenth of the tokens of HTML.",
    cache: "The browser's local store. What's in the cache arrives on the next visit without the network.",
    Brotli: "The compression method the server uses to send this page. What travels through the wire is a fraction of what the browser unpacks.",
  },
  ask: {
    view: "Ask",
    title: "Ask this page",
    privacy: "Your question goes to Claude together with this page's facts, not to us. No history is stored, either here or there.",
    placeholder: "For example: Why does this page load so fast?",
    send: "Ask",
    sendHint: "Sends the question to Claude along with the facts from the tools.",
    thinking: "Claude is reading the facts …",
    offline: "Claude isn't reachable right now. This is an answer from the page itself, without a model.",
    offlinePill: "without Claude",
    fromClaude: "Claude",
    fromLocal: "Tools",
    you: "You",
    suggestions: ["Why does this page load so fast?", "What does the selected element do?", "What does LCP mean?", "How does Google read this page?", "What would make the page slower?"],
    facts: "What Claude sees",
    factsWhy: "Exactly these facts go along with your question: this visit's metrics, the selected element, the head tags, and the page's text as markdown. Nothing about you, no history beyond this tab.",
    tooLong: "Please ask something shorter, 600 characters at most.",
    error: "That didn't work",
    clear: "Clear history",
    clearHint: "Clears the conversation in this tab.",
    noSelection: "no element selected",
    factPage: "Page",
    factSelected: "Selected element",
    factPerf: "Metrics",
    factLongTasks: "long tasks",
    factHeadings: "headings",
    factCrawler: "For crawlers",
    factText: "Page text",
    factTextVal: (n) => `Markdown twin, ${n.toLocaleString("en-US")} characters`,
    factDevice: "Device",
    local: {
      fast: (fcp, lcp, long) => `Your browser measured: first content after ${fcp}, largest element after ${lcp}, ${long}. The reason is in the page itself: finished HTML from the server, embedded styles, little JavaScript, and no framework sitting between them at runtime.`,
      longNone: "no long task",
      longSome: (n) => `${n} long ${n === 1 ? "task" : "tasks"}`,
      term: (key, text, value) => (value ? `${key}: ${text} On this page, just measured: ${value}.` : `${key}: ${text}`),
      element: (label, rules, code) => `Selected: ${label}. ${rules} CSS ${rules === 1 ? "rule applies" : "rules apply"}${code ? `, and in the code it's under “${code}”.` : ", and it has no script of its own: plain HTML and CSS, and that's exactly why it's fast."} More is in the “Element” tab.`,
      noElement: "No element is selected yet. Press “Pick” and click one on the page, then I can explain it.",
      crawler: (title, h1, heads, ld) => `Google reads the title “${title}” first, then the headings: ${h1} h1 and ${heads} headings in total${ld ? `, plus structured data of type ${ld}` : ""}. The “Google & AI” tab shows every stop.`,
      slower: "The page would get slower from anything that waits before the first paint: third-party fonts, scripts in the head, a framework that repaints it on every change, images without dimensions, animations off-screen.",
      fallback: "There's nothing about that in the tools. Once Claude is reachable, it can answer the question using the page's text; otherwise info@mccain-digital.com can help.",
    },
  },
};
