# Builds the home page's JSON-LD graph out of data.js, so the structured data
# and the visible copy can never drift apart.
#
# The FAQ is the important part: on the home page the questions and answers are
# rendered by v3.js at runtime, so a crawler that does not execute JavaScript
# sees an empty panel. FAQPage puts the same words in the markup where every
# crawler and every AI agent can read them without running anything.
import io
import subprocess
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SITE = "https://mccain-digital.com"

MARK_A = "  <!-- STRUCTURED DATA: generated by tools/build_jsonld.py, do not hand-edit -->"
MARK_B = "  <!-- /STRUCTURED DATA -->"


def read_data_js():
    """Read SERVICES and FAQ out of data.js by RUNNING it.

    This used to match them with a regex, and the regex was quietly wrong: it
    required every answer to be a double-quoted literal, so the seventh FAQ
    entry never reached the graph and the page shipped six questions where the
    console answered seven. Nobody noticed, because a generator that finds six
    of seven prints a cheerful "6 FAQ entries" and exits 0.

    data.js is an IIFE that assigns to `window`, which is exactly what
    api/ask.js already relies on - so a window stub and one node call give the
    real objects instead of an approximation of them. Any answer built from
    another value (the timing line is composed from RANGES now) comes through
    correct, and so does anything added later that a pattern would have missed.
    """
    script = (
        "global.window = {};"
        "require(process.argv[1]);"
        "const M = global.window.MCD || {};"
        "process.stdout.write(JSON.stringify({"
        "  services: (M.SERVICES || []).map(s => ({ n: s.n, h: s.h, href: s.href, p: s.p })),"
        "  faq: (M.FAQ || []).map(f => ({ q: f.q, a: f.a }))"
        "}));"
    )
    out = subprocess.run(
        ["node", "-e", script, os.path.join(ROOT, "data.js")],
        capture_output=True, text=True, encoding="utf-8",
    )
    if out.returncode != 0:
        raise SystemExit("node could not read data.js:\n" + (out.stderr or "").strip())
    data = json.loads(out.stdout)

    strip = lambda t: " ".join(
        re.sub(r"<[^>]+>", "", t)
        .replace("&amp;", "&").replace("&ldquo;", '"').replace("&rdquo;", '"')
        .split()
    )
    services = [dict(s, p=strip(s["p"])) for s in data["services"]]
    faq = [{"q": f["q"], "a": strip(f["a"])} for f in data["faq"]]
    return services, faq


SERVICES, FAQ = read_data_js()
# The FAQ count is asserted against data.js itself, not against a floor. A
# floor of 5 is what let a missing seventh entry pass for as long as it did.
FAQ_IN_SOURCE = io.open(os.path.join(ROOT, "data.js"), encoding="utf-8").read()
FAQ_IN_SOURCE = FAQ_IN_SOURCE[FAQ_IN_SOURCE.index("const FAQ = ["):FAQ_IN_SOURCE.index("/* ---------- knowledge base")]
EXPECTED = len(re.findall(r"^\s*q: ", FAQ_IN_SOURCE, re.M))
if len(SERVICES) != 4 or len(FAQ) != EXPECTED:
    raise SystemExit("data.js read failed: %d services (want 4), %d faq (want %d)"
                     % (len(SERVICES), len(FAQ), EXPECTED))

ORG = {
    "@type": "ProfessionalService",
    "@id": SITE + "/#org",
    "name": "McCain Digital",
    "description": "Digital product studio in Bavaria. AI tools on your own data, web apps, websites and custom software.",
    "url": SITE + "/",
    "email": "info@mccain-digital.com",
    "foundingDate": "2016",
    "image": SITE + "/og-image.png",
    "logo": SITE + "/logo-mark-200.png",
    "priceRange": "$$$",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "Holderweg 1",
        "postalCode": "86869",
        "addressLocality": "Oberostendorf",
        "addressRegion": "Bavaria",
        "addressCountry": "DE",
    },
    "areaServed": {"@type": "Country", "name": "Germany"},
    "founder": [
        {"@type": "Person", "name": "Christian Mc Cain", "jobTitle": "Co-founder — builds & ships"},
        {"@type": "Person", "name": "Kathrin Mc Cain", "jobTitle": "Co-founder — design & brand"},
    ],
    "numberOfEmployees": {"@type": "QuantitativeValue", "value": 2},
    "openingHoursSpecification": {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "opens": "09:00",
        "closes": "18:00",
    },
    "hasOfferCatalog": {
        "@type": "OfferCatalog",
        "name": "Services",
        "itemListElement": [
            {
                "@type": "Offer",
                "itemOffered": {
                    "@type": "Service",
                    "name": s["h"],
                    "description": s["p"],
                    "url": SITE + "/" + s["href"],
                },
            }
            for s in SERVICES
        ],
    },
}

GRAPH = {
    "@context": "https://schema.org",
    "@graph": [
        ORG,
        {
            "@type": "WebSite",
            "@id": SITE + "/#website",
            "url": SITE + "/",
            "name": "McCain Digital",
            "publisher": {"@id": SITE + "/#org"},
            "inLanguage": "en",
        },
        {
            "@type": "FAQPage",
            "@id": SITE + "/#faq",
            "mainEntity": [
                {
                    "@type": "Question",
                    "name": f["q"],
                    "acceptedAnswer": {"@type": "Answer", "text": f["a"]},
                }
                for f in FAQ
            ],
        },
    ],
}

payload = json.dumps(GRAPH, ensure_ascii=False, indent=2)
payload = "\n".join("  " + ln for ln in payload.split("\n"))
new = MARK_A + '\n  <script type="application/ld+json">\n' + payload + "\n  </script>\n" + MARK_B

p = os.path.join(ROOT, "index.html")
s = io.open(p, encoding="utf-8", newline="").read()
if MARK_A in s:
    a = s.index(MARK_A)
    b = s.index(MARK_B) + len(MARK_B)
    s = s[:a] + new + s[b:]
else:
    anchor = s.index("</head>")
    s = s[:anchor] + new + "\n" + s[anchor:]
io.open(p, "w", encoding="utf-8", newline="").write(s)
print("index.html: %d services, %d FAQ entries in the graph" % (len(SERVICES), len(FAQ)))
