# Builds the home page's JSON-LD graph out of data.js, so the structured data
# and the visible copy can never drift apart.
#
# The FAQ is the important part: on the home page the questions and answers are
# rendered by v3.js at runtime, so a crawler that does not execute JavaScript
# sees an empty panel. FAQPage puts the same words in the markup where every
# crawler and every AI agent can read them without running anything.
import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SITE = "https://mccain-digital.com"

MARK_A = "  <!-- STRUCTURED DATA: generated by tools/build_jsonld.py, do not hand-edit -->"
MARK_B = "  <!-- /STRUCTURED DATA -->"


def read_data_js():
    """Pull SERVICES and FAQ out of data.js without a JS engine."""
    s = io.open(os.path.join(ROOT, "data.js"), encoding="utf-8").read()

    services = []
    block = s[s.index("const SERVICES = ["):s.index("/* ---------- everything the menu")]
    for m in re.finditer(r'n:\s*"(\d+)",\s*h:\s*"([^"]+)",\s*slug:\s*"([^"]+)",\s*href:\s*"([^"]+)",\s*\n?\s*p:\s*"([^"]+)"', block):
        services.append({"n": m.group(1), "h": m.group(2), "href": m.group(4), "p": m.group(5)})

    faq = []
    fblock = s[s.index("const FAQ = ["):s.index("/* ---------- knowledge base")]
    for m in re.finditer(r'q:\s*"((?:[^"\\]|\\.)*)",\s*\n?\s*a:\s*"((?:[^"\\]|\\.)*)"', fblock):
        q = m.group(1).replace('\\"', '"')
        a = m.group(2).replace('\\"', '"').replace("\\n", "\n")
        a = re.sub(r"<[^>]+>", "", a)                    # plain text for the schema
        a = a.replace("&amp;", "&").replace("&ldquo;", '"').replace("&rdquo;", '"')
        faq.append({"q": q, "a": " ".join(a.split())})
    return services, faq


SERVICES, FAQ = read_data_js()
if len(SERVICES) != 4 or len(FAQ) < 5:
    raise SystemExit("data.js parse failed: %d services, %d faq" % (len(SERVICES), len(FAQ)))

ORG = {
    "@type": "ProfessionalService",
    "@id": SITE + "/#org",
    "name": "McCain Digital",
    "description": "Digital product studio in Bavaria. AI tools on your own data, web apps, websites and custom software.",
    "url": SITE + "/",
    "email": "info@mccain-digital.com",
    "foundingDate": "2016",
    "image": SITE + "/og-image.png",
    "logo": SITE + "/logo-mark-200.png",
    "priceRange": "$$$",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "Holderweg 1",
        "postalCode": "86869",
        "addressLocality": "Oberostendorf",
        "addressRegion": "Bavaria",
        "addressCountry": "DE",
    },
    "areaServed": {"@type": "Country", "name": "Germany"},
    "founder": [
        {"@type": "Person", "name": "Christian Mc Cain", "jobTitle": "Co-founder — builds & ships"},
        {"@type": "Person", "name": "Kathrin Mc Cain", "jobTitle": "Co-founder — design & brand"},
    ],
    "numberOfEmployees": {"@type": "QuantitativeValue", "value": 2},
    "openingHoursSpecification": {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "opens": "09:00",
        "closes": "18:00",
    },
    "hasOfferCatalog": {
        "@type": "OfferCatalog",
        "name": "Services",
        "itemListElement": [
            {
                "@type": "Offer",
                "itemOffered": {
                    "@type": "Service",
                    "name": s["h"],
                    "description": s["p"],
                    "url": SITE + "/" + s["href"],
                },
            }
            for s in SERVICES
        ],
    },
}

GRAPH = {
    "@context": "https://schema.org",
    "@graph": [
        ORG,
        {
            "@type": "WebSite",
            "@id": SITE + "/#website",
            "url": SITE + "/",
            "name": "McCain Digital",
            "publisher": {"@id": SITE + "/#org"},
            "inLanguage": "en",
        },
        {
            "@type": "FAQPage",
            "@id": SITE + "/#faq",
            "mainEntity": [
                {
                    "@type": "Question",
                    "name": f["q"],
                    "acceptedAnswer": {"@type": "Answer", "text": f["a"]},
                }
                for f in FAQ
            ],
        },
    ],
}

payload = json.dumps(GRAPH, ensure_ascii=False, indent=2)
payload = "\n".join("  " + ln for ln in payload.split("\n"))
new = MARK_A + '\n  <script type="application/ld+json">\n' + payload + "\n  </script>\n" + MARK_B

p = os.path.join(ROOT, "index.html")
s = io.open(p, encoding="utf-8", newline="").read()
if MARK_A in s:
    a = s.index(MARK_A)
    b = s.index(MARK_B) + len(MARK_B)
    s = s[:a] + new + s[b:]
else:
    anchor = s.index("</head>")
    s = s[:anchor] + new + "\n" + s[anchor:]
io.open(p, "w", encoding="utf-8", newline="").write(s)
print("index.html: %d services, %d FAQ entries in the graph" % (len(SERVICES), len(FAQ)))
